"""add chat with agent in document PdfViewer and OfficeViewer

Revision ID: 003e09d253c1
Revises: a9df1fdc92b7
Create Date: 2026-07-10 10:18:04.234334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003e09d253c1'
down_revision: Union[str, None] = 'a9df1fdc92b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('context_type', sa.String(length=32), nullable=True))
    op.add_column('chat_conversations', sa.Column('context_id', sa.String(length=64), nullable=True))
    op.add_column('chat_conversations', sa.Column('context_title', sa.String(length=500), nullable=True))
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_tsv_gin', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_material_summaries_material_type_material_id'), table_name='material_summaries')
    op.create_index(op.f('ix_material_summaries_id'), 'material_summaries', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_summaries_id'), table_name='material_summaries')
    op.create_index(op.f('ix_material_summaries_material_type_material_id'), 'material_summaries', ['material_type', 'id'], unique=False)
    op.drop_index('ix_document_chunks_tsv_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('chat_conversations', 'context_title')
    op.drop_column('chat_conversations', 'context_id')
    op.drop_column('chat_conversations', 'context_type')
    # ### end Alembic commands ###
