"""remove fields pagesRead and coverimage from library_materials

Revision ID: 020feca81dfb
Revises: cfe3ac278d25
Create Date: 2026-06-18 08:47:01.325560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020feca81dfb'
down_revision: Union[str, None] = 'cfe3ac278d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_materials', 'pagesRead')
    op.drop_column('library_materials', 'coverimage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_materials', sa.Column('coverimage', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('library_materials', sa.Column('pagesRead', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
