"""Introduce is_external column to User

Revision ID: 03e943e92e0d
Revises: e7a1c5f3b4d2
Create Date: 2026-05-20 10:02:45.027107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e943e92e0d'
down_revision: Union[str, None] = 'e7a1c5f3b4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    op.add_column('users', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_external=false")
    op.alter_column('users','is_external',nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_external')
    # op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
