"""Introduce Photo and Siganture columns

Revision ID: 04fcd61bc533
Revises: cf3807113c3a
Create Date: 2026-05-11 10:14:11.099255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fcd61bc533'
down_revision: Union[str, None] = 'cf3807113c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.add_column('profiles', sa.Column('signature', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'signature')
    op.drop_column('profiles', 'photo')
    # ### end Alembic commands ###
