"""Student mapping changed to user

Revision ID: 18e11725ed9f
Revises: a3f497962ba9
Create Date: 2026-06-25 07:37:09.126832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e11725ed9f'
down_revision: Union[str, None] = 'a3f497962ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendances_student_id_fkey'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_student_id_fkey'), 'attendances', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
