"""Attendance Status table

Revision ID: 1e821e1403fb
Revises: c0u2r3s4e5l6
Create Date: 2026-06-12 08:24:10.100870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e821e1403fb'
down_revision: Union[str, None] = 'c0u2r3s4e5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_attendance_status_code')
    )
    op.add_column('attendances', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'attendance_status', ['status_id'], ['id'])
    op.drop_column('attendances', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'SIMULATION', 'FLYING', name='attendancestatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'status_id')
    op.drop_table('attendance_status')
    # ### end Alembic commands ###
