"""Lesson content release completion

Revision ID: 23b3e88ffe89
Revises: f6s7e8l9c0a1
Create Date: 2026-06-23 07:13:31.501952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b3e88ffe89'
down_revision: Union[str, None] = 'f6s7e8l9c0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_selection_lesson_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_instance_id', 'lesson_id', 'content_type', 'content_id', 'student_id', name='uq_cs_lesson_completion')
    )
    op.create_index(op.f('ix_course_selection_lesson_completions_course_instance_id'), 'course_selection_lesson_completions', ['course_instance_id'], unique=False)
    op.create_index(op.f('ix_course_selection_lesson_completions_lesson_id'), 'course_selection_lesson_completions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_course_selection_lesson_completions_student_id'), 'course_selection_lesson_completions', ['student_id'], unique=False)
    op.create_table('course_selection_lesson_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_instance_id', 'lesson_id', 'content_type', 'content_id', name='uq_cs_lesson_release')
    )
    op.create_index(op.f('ix_course_selection_lesson_releases_course_instance_id'), 'course_selection_lesson_releases', ['course_instance_id'], unique=False)
    op.create_index(op.f('ix_course_selection_lesson_releases_lesson_id'), 'course_selection_lesson_releases', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_selection_lesson_releases_lesson_id'), table_name='course_selection_lesson_releases')
    op.drop_index(op.f('ix_course_selection_lesson_releases_course_instance_id'), table_name='course_selection_lesson_releases')
    op.drop_table('course_selection_lesson_releases')
    op.drop_index(op.f('ix_course_selection_lesson_completions_student_id'), table_name='course_selection_lesson_completions')
    op.drop_index(op.f('ix_course_selection_lesson_completions_lesson_id'), table_name='course_selection_lesson_completions')
    op.drop_index(op.f('ix_course_selection_lesson_completions_course_instance_id'), table_name='course_selection_lesson_completions')
    op.drop_table('course_selection_lesson_completions')
    # ### end Alembic commands ###
