"""Update Lesson Detail

Revision ID: 268b684c9e7c
Revises: 18e11725ed9f
Create Date: 2026-06-26 06:23:15.134017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268b684c9e7c'
down_revision: Union[str, None] = '18e11725ed9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('session_placement_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_attendance_record'), 'attendances', type_='unique')
    op.create_index('uq_attendance_record', 'attendances', ['student_id', 'lesson_id', 'date'], unique=True, postgresql_where=sa.text('session_placement_id IS NULL'))
    op.create_index(op.f('ix_attendances_session_placement_id'), 'attendances', ['session_placement_id'], unique=False)
    op.create_index('uq_attendance_session_placement', 'attendances', ['student_id', 'session_placement_id'], unique=True, postgresql_where=sa.text('session_placement_id IS NOT NULL'))
    op.create_foreign_key(None, 'attendances', 'course_session_schedule_placements', ['session_placement_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_session_schedule_placements', sa.Column('start_minute', sa.Integer(), nullable=False))
    op.add_column('course_session_schedule_placements', sa.Column('duration_minute', sa.Integer(), nullable=False))
    op.alter_column('course_session_schedule_placements', 'start_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course_session_schedule_placements', 'span',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_session_schedule_placements', 'span',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_session_schedule_placements', 'start_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('course_session_schedule_placements', 'duration_minute')
    op.drop_column('course_session_schedule_placements', 'start_minute')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_index('uq_attendance_session_placement', table_name='attendances', postgresql_where=sa.text('session_placement_id IS NOT NULL'))
    op.drop_index(op.f('ix_attendances_session_placement_id'), table_name='attendances')
    op.drop_index('uq_attendance_record', table_name='attendances', postgresql_where=sa.text('session_placement_id IS NULL'))
    op.create_unique_constraint(op.f('uq_attendance_record'), 'attendances', ['student_id', 'lesson_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendances', 'session_placement_id')
    # ### end Alembic commands ###
