"""Survery initial migration script

Revision ID: 282e9c8f1780
Revises: 6719f7bab0fe
Create Date: 2026-06-06 04:21:17.881278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '282e9c8f1780'
down_revision: Union[str, None] = '6719f7bab0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_question_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether answering this question is mandatory'),
    sa.Column('allow_multiple', sa.Boolean(), server_default=sa.text("'false'"), nullable=False, comment='Whether to show checkboxes (multiple) instead of radio (single)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_question_pool_id'), 'survey_question_pool', ['id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_table('survey_pool_answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True, comment='Optional weight used for scoring; null = default 1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question_pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_pool_answer_options_id'), 'survey_pool_answer_options', ['id'], unique=False)
    op.create_index(op.f('ix_survey_pool_answer_options_question_id'), 'survey_pool_answer_options', ['question_id'], unique=False)
    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('pool_question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether answering this question is mandatory'),
    sa.Column('allow_multiple', sa.Boolean(), server_default=sa.text("'false'"), nullable=False, comment='Whether to show checkboxes (multiple) instead of radio (single)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_question_id'], ['survey_question_pool.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_id'), 'survey_questions', ['id'], unique=False)
    op.create_index(op.f('ix_survey_questions_survey_id'), 'survey_questions', ['survey_id'], unique=False)
    op.create_table('survey_student_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_started', sa.Boolean(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=True),
    sa.Column('overall_grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_student_responses_id'), 'survey_student_responses', ['id'], unique=False)
    op.create_index(op.f('ix_survey_student_responses_survey_id'), 'survey_student_responses', ['survey_id'], unique=False)
    op.create_table('survey_answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True, comment='Optional weight used for scoring; null = default 1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_answer_options_id'), 'survey_answer_options', ['id'], unique=False)
    op.create_index(op.f('ix_survey_answer_options_question_id'), 'survey_answer_options', ['question_id'], unique=False)
    #op.drop_index(op.f('ix_audit_logs_table_row'), table_name='audit_logs')
    #op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    #op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    #op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    #op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    #op.alter_column('quizzes', 'type',
    #           existing_type=sa.VARCHAR(length=32),
    #           nullable=False)
    #op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               existing_nullable=False)
    #op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    #op.alter_column('quizzes', 'type',
    #           existing_type=sa.VARCHAR(length=32),
    #           nullable=True)
    #op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    #op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    #op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    #op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    #op.create_index(op.f('ix_audit_logs_table_row'), 'audit_logs', ['table_name', 'row_id'], unique=False)
    op.drop_index(op.f('ix_survey_answer_options_question_id'), table_name='survey_answer_options')
    op.drop_index(op.f('ix_survey_answer_options_id'), table_name='survey_answer_options')
    op.drop_table('survey_answer_options')
    op.drop_index(op.f('ix_survey_student_responses_survey_id'), table_name='survey_student_responses')
    op.drop_index(op.f('ix_survey_student_responses_id'), table_name='survey_student_responses')
    op.drop_table('survey_student_responses')
    op.drop_index(op.f('ix_survey_questions_survey_id'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_questions_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_survey_pool_answer_options_question_id'), table_name='survey_pool_answer_options')
    op.drop_index(op.f('ix_survey_pool_answer_options_id'), table_name='survey_pool_answer_options')
    op.drop_table('survey_pool_answer_options')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_survey_question_pool_id'), table_name='survey_question_pool')
    op.drop_table('survey_question_pool')
    # ### end Alembic commands ###
