"""Introduce RAG improvement avoid duplicate chunk

Revision ID: 3d3c4cd07051
Revises: 5f4ac52f849e
Create Date: 2026-07-13 12:57:54.098091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3c4cd07051'
down_revision: Union[str, None] = '5f4ac52f849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
