"""Removed unused fields in student and teacher and introduce course_enrollments and courses_instructors

Revision ID: 53b190edf7f3
Revises: 19ff422c3cfe
Create Date: 2026-06-10 08:07:32.543691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b190edf7f3'
down_revision: Union[str, None] = '19ff422c3cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_instance_id', 'enrollment_date', name='uq_student_enrollment')
    )
    op.create_table('course_instructors',
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_instance_id', 'instructor_id')
    )

    # op.add_column('attendances', sa.Column('user_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'attendances', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    # op.drop_index(op.f('ix_course_info_entry_standards_general_id'), table_name='course_info_entry_standards')
    # op.create_index(op.f('ix_course_info_entry_standards_course_entry_standard_id'), 'course_info_entry_standards', ['course_entry_standard_id'], unique=False)
    # op.create_index(op.f('ix_course_info_entry_standards_course_info_general_id'), 'course_info_entry_standards', ['course_info_general_id'], unique=False)
    # op.drop_column('course_info_entry_standards', 'created_at')
    # op.drop_column('course_info_entry_standards', 'updated_at')
    # op.drop_constraint(op.f('uq_course_info_general_course_info_id'), 'course_info_general', type_='unique')
    # op.drop_index(op.f('ix_course_info_general_course_info_id'), table_name='course_info_general')
    # op.create_index(op.f('ix_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], unique=True)
    # op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_pr_id'), table_name='course_info_instructor_qualification_requirements')
    # op.create_index(op.f('ix_course_info_instructor_qualification_requirements_course_info_personnel_requirement_id'), 'course_info_instructor_qualification_requirements', ['course_info_personnel_requirement_id'], unique=False)
    # op.create_index(op.f('ix_course_info_instructor_qualification_requirements_instructor_qualification_requirement_id'), 'course_info_instructor_qualification_requirements', ['instructor_qualification_requirement_id'], unique=False)
    # op.drop_column('course_info_instructor_qualification_requirements', 'created_at')
    # op.drop_column('course_info_instructor_qualification_requirements', 'updated_at')
    # op.drop_constraint(op.f('uq_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', type_='unique')
    # op.drop_index(op.f('ix_course_info_lesson_creation_course_info_id'), table_name='course_info_lesson_creation')
    # op.create_index(op.f('ix_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], unique=True)
    # op.drop_index(op.f('ix_course_info_lesson_creation_lesson_units_lesson_id'), table_name='course_info_lesson_creation_lesson_units')
    # op.create_index(op.f('ix_course_info_lesson_creation_lesson_units_course_info_lesson_creation_lesson_id'), 'course_info_lesson_creation_lesson_units', ['course_info_lesson_creation_lesson_id'], unique=False)
    # op.drop_column('course_info_lesson_creation_lesson_units', 'created_at')
    # op.drop_column('course_info_lesson_creation_lesson_units', 'updated_at')
    # op.drop_index(op.f('ix_course_info_lesson_creation_lessons_parent_id'), table_name='course_info_lesson_creation_lessons')
    # op.create_index(op.f('ix_course_info_lesson_creation_lessons_course_info_lesson_creation_id'), 'course_info_lesson_creation_lessons', ['course_info_lesson_creation_id'], unique=False)
    # op.drop_column('course_info_lesson_creation_lessons', 'created_at')
    # op.drop_column('course_info_lesson_creation_lessons', 'updated_at')
    # op.drop_constraint(op.f('uq_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', type_='unique')
    # op.drop_index(op.f('ix_course_info_lesson_planning_course_info_id'), table_name='course_info_lesson_planning')
    # op.create_index(op.f('ix_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], unique=True)
    # op.drop_index(op.f('ix_cilp_classification_of_periods_lp_id'), table_name='course_info_lesson_planning_classification_of_periods')
    # op.create_index(op.f('ix_course_info_lesson_planning_classification_of_periods_course_info_lesson_planning_id'), 'course_info_lesson_planning_classification_of_periods', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_cilp_enabling_objectives_lp_id'), table_name='course_info_lesson_planning_enabling_objectives')
    # op.create_index(op.f('ix_course_info_lesson_planning_enabling_objectives_course_info_lesson_planning_id'), 'course_info_lesson_planning_enabling_objectives', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_cilp_environments_lp_id'), table_name='course_info_lesson_planning_environments')
    # op.create_index(op.f('ix_course_info_lesson_planning_environments_course_info_lesson_planning_id'), 'course_info_lesson_planning_environments', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_cilp_teaching_points_lp_id'), table_name='course_info_lesson_planning_teaching_points')
    # op.create_index(op.f('ix_course_info_lesson_planning_teaching_points_course_info_lesson_planning_id'), 'course_info_lesson_planning_teaching_points', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_cilp_training_objectives_lp_id'), table_name='course_info_lesson_planning_training_objectives')
    # op.create_index(op.f('ix_course_info_lesson_planning_training_objectives_course_info_lesson_planning_id'), 'course_info_lesson_planning_training_objectives', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_cilp_type_of_periods_lp_id'), table_name='course_info_lesson_planning_type_of_periods')
    # op.create_index(op.f('ix_course_info_lesson_planning_type_of_periods_course_info_lesson_planning_id'), 'course_info_lesson_planning_type_of_periods', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_constraint(op.f('uq_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', type_='unique')
    # op.drop_index(op.f('ix_course_info_personnel_requirement_course_info_id'), table_name='course_info_personnel_requirement')
    # op.create_index(op.f('ix_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], unique=True)
    # op.drop_constraint(op.f('uq_course_info_resources_course_info_id'), 'course_info_resources', type_='unique')
    # op.drop_index(op.f('ix_course_info_resources_course_info_id'), table_name='course_info_resources')
    # op.create_index(op.f('ix_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], unique=True)
    # op.drop_index(op.f('ix_cir_aircraft_armament_res_id'), table_name='course_info_resources_aircraft_armament_items')
    # op.create_index(op.f('ix_course_info_resources_aircraft_armament_items_course_info_resources_id'), 'course_info_resources_aircraft_armament_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_aircraft_items_resources_id'), table_name='course_info_resources_aircraft_items')
    # op.create_index(op.f('ix_course_info_resources_aircraft_items_course_info_resources_id'), 'course_info_resources_aircraft_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_aircraft_mission_equip_res_id'), table_name='course_info_resources_aircraft_mission_equipment_items')
    # op.create_index(op.f('ix_course_info_resources_aircraft_mission_equipment_items_course_info_resources_id'), 'course_info_resources_aircraft_mission_equipment_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_aviation_life_support_res_id'), table_name='course_info_resources_aviation_life_support_items')
    # op.create_index(op.f('ix_course_info_resources_aviation_life_support_items_course_info_resources_id'), 'course_info_resources_aviation_life_support_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_classroom_req_res_id'), table_name='course_info_resources_classroom_requirement_items')
    # op.create_index(op.f('ix_course_info_resources_classroom_requirement_items_course_info_resources_id'), 'course_info_resources_classroom_requirement_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_ground_armament_res_id'), table_name='course_info_resources_ground_armament_items')
    # op.create_index(op.f('ix_course_info_resources_ground_armament_items_course_info_resources_id'), 'course_info_resources_ground_armament_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_ground_maintenance_res_id'), table_name='course_info_resources_ground_maintenance_items')
    # op.create_index(op.f('ix_course_info_resources_ground_maintenance_items_course_info_resources_id'), 'course_info_resources_ground_maintenance_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_mission_plan_sys_res_id'), table_name='course_info_resources_mission_planning_system_items')
    # op.create_index(op.f('ix_course_info_resources_mission_planning_system_items_course_info_resources_id'), 'course_info_resources_mission_planning_system_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_personal_flight_equip_res_id'), table_name='course_info_resources_personal_flight_equipment_items')
    # op.create_index(op.f('ix_course_info_resources_personal_flight_equipment_items_course_info_resources_id'), 'course_info_resources_personal_flight_equipment_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_simulator_type_res_id'), table_name='course_info_resources_simulator_type_items')
    # op.create_index(op.f('ix_course_info_resources_simulator_type_items_course_info_resources_id'), 'course_info_resources_simulator_type_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_cir_training_material_aid_res_id'), table_name='course_info_resources_training_material_aid_items')
    # op.create_index(op.f('ix_course_info_resources_training_material_aid_items_course_info_resources_id'), 'course_info_resources_training_material_aid_items', ['course_info_resources_id'], unique=False)
    # op.drop_constraint(op.f('uq_course_infos_course_master_id'), 'course_infos', type_='unique')
    # op.drop_index(op.f('ix_course_infos_course_master_id'), table_name='course_infos')
    # op.create_index(op.f('ix_course_infos_course_master_id'), 'course_infos', ['course_master_id'], unique=True)
    # op.drop_index(op.f('ix_course_instances_master_id'), table_name='course_instances')
    # op.drop_index(op.f('ix_course_modification_requests_course_id'), table_name='course_modification_requests')
    # op.drop_constraint(op.f('course_modification_requests_course_id_fkey'), 'course_modification_requests', type_='foreignkey')
    # op.create_foreign_key(None, 'course_modification_requests', 'course_instances', ['course_id'], ['id'])
    # op.drop_constraint(op.f('uq_course_schedules_course_master_id'), 'course_schedules', type_='unique')
    # op.drop_index(op.f('ix_course_schedules_course_master_id'), table_name='course_schedules')
    # op.create_index(op.f('ix_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], unique=True)
    # op.drop_constraint(op.f('uq_evaluations_course_master_id'), 'evaluations', type_='unique')
    # op.drop_index(op.f('ix_evaluations_course_master_id'), table_name='evaluations')
    # op.create_index(op.f('ix_evaluations_course_master_id'), 'evaluations', ['course_master_id'], unique=True)
    # op.drop_constraint(op.f('uq_form_builders_course_master_id'), 'form_builders', type_='unique')
    # op.drop_index(op.f('ix_form_builders_course_master_id'), table_name='form_builders')
    # op.create_index(op.f('ix_form_builders_course_master_id'), 'form_builders', ['course_master_id'], unique=True)
    # op.drop_constraint(op.f('uq_materials_course_master_id'), 'materials', type_='unique')
    # op.drop_index(op.f('ix_materials_course_master_id'), table_name='materials')
    # op.create_index(op.f('ix_materials_course_master_id'), 'materials', ['course_master_id'], unique=True)
    
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_constraint(op.f('students_program_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'enrollment_date')
    op.drop_column('students', 'student_id')
    op.drop_column('students', 'program_id')
    op.drop_column('students', 'current_semester')
    op.drop_index(op.f('ix_teachers_employee_id'), table_name='teachers')
    op.drop_constraint(op.f('teachers_department_id_fkey'), 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'specialization')
    op.drop_column('teachers', 'department_id')
    op.drop_column('teachers', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('employee_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teachers_department_id_fkey'), 'teachers', 'departments', ['department_id'], ['id'])
    op.create_index(op.f('ix_teachers_employee_id'), 'teachers', ['employee_id'], unique=True)
    op.add_column('students', sa.Column('current_semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('enrollment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_program_id_fkey'), 'students', 'programs', ['program_id'], ['id'])
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    
    # op.drop_index(op.f('ix_materials_course_master_id'), table_name='materials')
    # op.create_index(op.f('ix_materials_course_master_id'), 'materials', ['course_master_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_materials_course_master_id'), 'materials', ['course_master_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_form_builders_course_master_id'), table_name='form_builders')
    # op.create_index(op.f('ix_form_builders_course_master_id'), 'form_builders', ['course_master_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_form_builders_course_master_id'), 'form_builders', ['course_master_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_evaluations_course_master_id'), table_name='evaluations')
    # op.create_index(op.f('ix_evaluations_course_master_id'), 'evaluations', ['course_master_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_evaluations_course_master_id'), 'evaluations', ['course_master_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_course_schedules_course_master_id'), table_name='course_schedules')
    # op.create_index(op.f('ix_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], postgresql_nulls_not_distinct=False)
    # op.drop_constraint(None, 'course_modification_requests', type_='foreignkey')
    # op.create_foreign_key(op.f('course_modification_requests_course_id_fkey'), 'course_modification_requests', 'course_instances', ['course_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_course_modification_requests_course_id'), 'course_modification_requests', ['course_id'], unique=False)
    # op.create_index(op.f('ix_course_instances_master_id'), 'course_instances', ['master_id'], unique=False)
    # op.drop_index(op.f('ix_course_infos_course_master_id'), table_name='course_infos')
    # op.create_index(op.f('ix_course_infos_course_master_id'), 'course_infos', ['course_master_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_infos_course_master_id'), 'course_infos', ['course_master_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_course_info_resources_training_material_aid_items_course_info_resources_id'), table_name='course_info_resources_training_material_aid_items')
    # op.create_index(op.f('ix_cir_training_material_aid_res_id'), 'course_info_resources_training_material_aid_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_simulator_type_items_course_info_resources_id'), table_name='course_info_resources_simulator_type_items')
    # op.create_index(op.f('ix_cir_simulator_type_res_id'), 'course_info_resources_simulator_type_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_personal_flight_equipment_items_course_info_resources_id'), table_name='course_info_resources_personal_flight_equipment_items')
    # op.create_index(op.f('ix_cir_personal_flight_equip_res_id'), 'course_info_resources_personal_flight_equipment_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_mission_planning_system_items_course_info_resources_id'), table_name='course_info_resources_mission_planning_system_items')
    # op.create_index(op.f('ix_cir_mission_plan_sys_res_id'), 'course_info_resources_mission_planning_system_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_ground_maintenance_items_course_info_resources_id'), table_name='course_info_resources_ground_maintenance_items')
    # op.create_index(op.f('ix_cir_ground_maintenance_res_id'), 'course_info_resources_ground_maintenance_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_ground_armament_items_course_info_resources_id'), table_name='course_info_resources_ground_armament_items')
    # op.create_index(op.f('ix_cir_ground_armament_res_id'), 'course_info_resources_ground_armament_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_classroom_requirement_items_course_info_resources_id'), table_name='course_info_resources_classroom_requirement_items')
    # op.create_index(op.f('ix_cir_classroom_req_res_id'), 'course_info_resources_classroom_requirement_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_aviation_life_support_items_course_info_resources_id'), table_name='course_info_resources_aviation_life_support_items')
    # op.create_index(op.f('ix_cir_aviation_life_support_res_id'), 'course_info_resources_aviation_life_support_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_aircraft_mission_equipment_items_course_info_resources_id'), table_name='course_info_resources_aircraft_mission_equipment_items')
    # op.create_index(op.f('ix_cir_aircraft_mission_equip_res_id'), 'course_info_resources_aircraft_mission_equipment_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_aircraft_items_course_info_resources_id'), table_name='course_info_resources_aircraft_items')
    # op.create_index(op.f('ix_course_info_resources_aircraft_items_resources_id'), 'course_info_resources_aircraft_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_aircraft_armament_items_course_info_resources_id'), table_name='course_info_resources_aircraft_armament_items')
    # op.create_index(op.f('ix_cir_aircraft_armament_res_id'), 'course_info_resources_aircraft_armament_items', ['course_info_resources_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_resources_course_info_id'), table_name='course_info_resources')
    # op.create_index(op.f('ix_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_course_info_personnel_requirement_course_info_id'), table_name='course_info_personnel_requirement')
    # op.create_index(op.f('ix_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_type_of_periods_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_type_of_periods')
    # op.create_index(op.f('ix_cilp_type_of_periods_lp_id'), 'course_info_lesson_planning_type_of_periods', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_training_objectives_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_training_objectives')
    # op.create_index(op.f('ix_cilp_training_objectives_lp_id'), 'course_info_lesson_planning_training_objectives', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_teaching_points_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_teaching_points')
    # op.create_index(op.f('ix_cilp_teaching_points_lp_id'), 'course_info_lesson_planning_teaching_points', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_environments_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_environments')
    # op.create_index(op.f('ix_cilp_environments_lp_id'), 'course_info_lesson_planning_environments', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_enabling_objectives_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_enabling_objectives')
    # op.create_index(op.f('ix_cilp_enabling_objectives_lp_id'), 'course_info_lesson_planning_enabling_objectives', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_classification_of_periods_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_classification_of_periods')
    # op.create_index(op.f('ix_cilp_classification_of_periods_lp_id'), 'course_info_lesson_planning_classification_of_periods', ['course_info_lesson_planning_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_planning_course_info_id'), table_name='course_info_lesson_planning')
    # op.create_index(op.f('ix_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], postgresql_nulls_not_distinct=False)
    # op.add_column('course_info_lesson_creation_lessons', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.add_column('course_info_lesson_creation_lessons', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_course_info_lesson_creation_lessons_course_info_lesson_creation_id'), table_name='course_info_lesson_creation_lessons')
    # op.create_index(op.f('ix_course_info_lesson_creation_lessons_parent_id'), 'course_info_lesson_creation_lessons', ['course_info_lesson_creation_id'], unique=False)
    # op.add_column('course_info_lesson_creation_lesson_units', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.add_column('course_info_lesson_creation_lesson_units', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_course_info_lesson_creation_lesson_units_course_info_lesson_creation_lesson_id'), table_name='course_info_lesson_creation_lesson_units')
    # op.create_index(op.f('ix_course_info_lesson_creation_lesson_units_lesson_id'), 'course_info_lesson_creation_lesson_units', ['course_info_lesson_creation_lesson_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_lesson_creation_course_info_id'), table_name='course_info_lesson_creation')
    # op.create_index(op.f('ix_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], postgresql_nulls_not_distinct=False)
    # op.add_column('course_info_instructor_qualification_requirements', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.add_column('course_info_instructor_qualification_requirements', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_instructor_qualification_requirement_id'), table_name='course_info_instructor_qualification_requirements')
    # op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_course_info_personnel_requirement_id'), table_name='course_info_instructor_qualification_requirements')
    # op.create_index(op.f('ix_course_info_instructor_qualification_requirements_pr_id'), 'course_info_instructor_qualification_requirements', ['course_info_personnel_requirement_id'], unique=False)
    # op.drop_index(op.f('ix_course_info_general_course_info_id'), table_name='course_info_general')
    # op.create_index(op.f('ix_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], postgresql_nulls_not_distinct=False)
    # op.add_column('course_info_entry_standards', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.add_column('course_info_entry_standards', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_course_info_entry_standards_course_info_general_id'), table_name='course_info_entry_standards')
    # op.drop_index(op.f('ix_course_info_entry_standards_course_entry_standard_id'), table_name='course_info_entry_standards')
    # op.create_index(op.f('ix_course_info_entry_standards_general_id'), 'course_info_entry_standards', ['course_info_general_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    # op.drop_constraint(None, 'attendances', type_='foreignkey')
    # op.drop_column('attendances', 'user_id')
    
    op.drop_table('course_instructors')
    op.drop_table('course_enrollments')
    # ### end Alembic commands ###
