"""course selection: own course information tables

Revision ID: 566c77962a20
Revises: a338d2726674
Create Date: 2026-06-17 12:43:12.667866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566c77962a20'
down_revision: Union[str, None] = 'a338d2726674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_selection_info_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('course_duration', sa.Integer(), nullable=True),
    sa.Column('programmed_working_frequency', sa.String(length=20), nullable=True),
    sa.Column('programmed_working_start_time', sa.Time(), nullable=True),
    sa.Column('programmed_working_end_time', sa.Time(), nullable=True),
    sa.Column('course_aim', sa.Text(), nullable=True),
    sa.Column('ctp_version', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_selection_info_general_course_instance_id'), 'course_selection_info_general', ['course_instance_id'], unique=True)
    op.create_table('course_selection_info_lesson_creation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_selection_info_lesson_creation_course_instance_id'), 'course_selection_info_lesson_creation', ['course_instance_id'], unique=True)
    op.create_table('course_selection_info_lesson_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('number_of_periods_per_day', sa.Integer(), nullable=True),
    sa.Column('number_of_training_days_per_week', sa.Float(), nullable=True),
    sa.Column('number_of_periods_per_half_day', sa.Integer(), nullable=True),
    sa.Column('period_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_selection_info_lesson_planning_course_instance_id'), 'course_selection_info_lesson_planning', ['course_instance_id'], unique=True)
    op.create_table('course_selection_info_personnel_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('maximum_trainees_number', sa.Integer(), nullable=True),
    sa.Column('minimum_trainees_number', sa.Integer(), nullable=True),
    sa.Column('instructors_to_trainees_ratio_flight', sa.String(length=100), nullable=True),
    sa.Column('instructors_to_trainees_ratio_classroom', sa.String(length=100), nullable=True),
    sa.Column('instructors_to_trainees_ratio_practical', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_personnel_req_instance_id', 'course_selection_info_personnel_requirement', ['course_instance_id'], unique=True)
    op.create_table('course_selection_info_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_selection_info_resources_course_instance_id'), 'course_selection_info_resources', ['course_instance_id'], unique=True)
    op.create_table('course_selection_info_entry_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_general_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('course_entry_standard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_entry_standard_id'], ['master_course_entry_standards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_general_id'], ['course_selection_info_general.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_entry_std_general_id', 'course_selection_info_entry_standards', ['course_selection_info_general_id'], unique=False)
    op.create_index('ix_csi_entry_std_master_id', 'course_selection_info_entry_standards', ['course_entry_standard_id'], unique=False)
    op.create_table('course_selection_info_instructor_qualification_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_personnel_requirement_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('instructor_qualification_requirement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_personnel_requirement_id'], ['course_selection_info_personnel_requirement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_qualification_requirement_id'], ['master_instructor_qualification_requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_instr_qual_req_master_id', 'course_selection_info_instructor_qualification_requirements', ['instructor_qualification_requirement_id'], unique=False)
    op.create_index('ix_csi_instr_qual_req_personnel_id', 'course_selection_info_instructor_qualification_requirements', ['course_selection_info_personnel_requirement_id'], unique=False)
    op.create_table('course_selection_info_lesson_creation_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_creation_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.String(length=50), nullable=True),
    sa.Column('lesson_title', sa.String(length=255), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('period_type_id', sa.Integer(), nullable=True),
    sa.Column('flight_timing', sa.Integer(), nullable=True),
    sa.Column('instructor_student_ratio', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('health_and_safety', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_creation_id'], ['course_selection_info_lesson_creation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['master_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_type_id'], ['master_period_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lc_lessons_lesson_creation_id', 'course_selection_info_lesson_creation_lessons', ['course_selection_info_lesson_creation_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_classification_of_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('classification_of_period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_of_period_id'], ['master_period_classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_classif_of_periods_lp_id', 'course_selection_info_lesson_planning_classification_of_periods', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_enabling_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('enabling_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enabling_objective_id'], ['master_enabling_objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_enabling_objectives_lp_id', 'course_selection_info_lesson_planning_enabling_objectives', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['master_environments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_environments_lp_id', 'course_selection_info_lesson_planning_environments', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_teaching_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('teaching_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_point_id'], ['master_teaching_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_teaching_points_lp_id', 'course_selection_info_lesson_planning_teaching_points', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_training_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('training_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_objective_id'], ['master_training_objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_training_objectives_lp_id', 'course_selection_info_lesson_planning_training_objectives', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_lesson_planning_type_of_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_planning_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type_of_period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_planning_id'], ['course_selection_info_lesson_planning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_of_period_id'], ['master_period_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lp_type_of_periods_lp_id', 'course_selection_info_lesson_planning_type_of_periods', ['course_selection_info_lesson_planning_id'], unique=False)
    op.create_table('course_selection_info_resources_acft_mission_equip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('aircraft_mission_equipment_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_mission_equipment_id'], ['master_aircraft_mission_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_acft_mission_eq_resources_id', 'course_selection_info_resources_acft_mission_equip_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_aircraft_armament_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('aircraft_armament_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_armament_id'], ['master_aircraft_armaments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_acft_armament_resources_id', 'course_selection_info_resources_aircraft_armament_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_aircraft_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=True),
    sa.Column('number_of_aircraft', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['master_aircraft_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_aircraft_resources_id', 'course_selection_info_resources_aircraft_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_aviation_life_support_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('aviation_life_support_equipment_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aviation_life_support_equipment_id'], ['master_aviation_life_support_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_aviation_life_supp_resources_id', 'course_selection_info_resources_aviation_life_support_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_classroom_requirement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('classroom_requirement_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_requirement_id'], ['master_classroom_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_classroom_req_resources_id', 'course_selection_info_resources_classroom_requirement_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_ground_armament_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('ground_armament_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ground_armament_id'], ['master_ground_armaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_ground_armament_resources_id', 'course_selection_info_resources_ground_armament_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_ground_maintenance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('ground_maintenance_equipment_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ground_maintenance_equipment_id'], ['master_ground_maintenance_equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_ground_maint_resources_id', 'course_selection_info_resources_ground_maintenance_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_mission_planning_system_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('mission_planning_system_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_planning_system_id'], ['master_mission_planning_systems.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_mission_plan_sys_resources_id', 'course_selection_info_resources_mission_planning_system_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_personal_flight_equipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('personal_flight_equipment_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personal_flight_equipment_id'], ['master_personal_flight_equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_personal_flight_eq_resources_id', 'course_selection_info_resources_personal_flight_equipment_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_simulator_type_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('simulator_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulator_type_id'], ['master_simulator_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_simulator_type_resources_id', 'course_selection_info_resources_simulator_type_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_resources_training_material_aid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_resources_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('training_material_aid_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_resources_id'], ['course_selection_info_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_material_aid_id'], ['master_training_material_aids.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_res_training_mat_aid_resources_id', 'course_selection_info_resources_training_material_aid_items', ['course_selection_info_resources_id'], unique=False)
    op.create_table('course_selection_info_lesson_creation_lesson_conducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_creation_lesson_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=20), nullable=True),
    sa.Column('point', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_creation_lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csilc_lesson_conducts_lesson_id', 'course_selection_info_lesson_creation_lesson_conducts', ['course_selection_info_lesson_creation_lesson_id'], unique=False)
    op.create_table('course_selection_info_lesson_creation_lesson_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_creation_lesson_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_creation_lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csilc_lesson_resources_lesson_id', 'course_selection_info_lesson_creation_lesson_resources', ['course_selection_info_lesson_creation_lesson_id'], unique=False)
    op.create_table('course_selection_info_lesson_creation_lesson_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_selection_info_lesson_creation_lesson_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('training_objective_id', sa.Integer(), nullable=True),
    sa.Column('enabling_objective_id', sa.Integer(), nullable=True),
    sa.Column('teaching_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_selection_info_lesson_creation_lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enabling_objective_id'], ['master_enabling_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teaching_point_id'], ['master_teaching_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_objective_id'], ['master_training_objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csi_lc_lesson_units_lesson_id', 'course_selection_info_lesson_creation_lesson_units', ['course_selection_info_lesson_creation_lesson_id'], unique=False)
    op.add_column('course_instances', sa.Column('course_info_completion', sa.Integer(), server_default='0', nullable=False))
    op.add_column('course_instances', sa.Column('course_info_seeded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_instances', 'course_info_seeded')
    op.drop_column('course_instances', 'course_info_completion')
    op.drop_index('ix_csi_lc_lesson_units_lesson_id', table_name='course_selection_info_lesson_creation_lesson_units')
    op.drop_table('course_selection_info_lesson_creation_lesson_units')
    op.drop_index('ix_csilc_lesson_resources_lesson_id', table_name='course_selection_info_lesson_creation_lesson_resources')
    op.drop_table('course_selection_info_lesson_creation_lesson_resources')
    op.drop_index('ix_csilc_lesson_conducts_lesson_id', table_name='course_selection_info_lesson_creation_lesson_conducts')
    op.drop_table('course_selection_info_lesson_creation_lesson_conducts')
    op.drop_index('ix_csi_res_training_mat_aid_resources_id', table_name='course_selection_info_resources_training_material_aid_items')
    op.drop_table('course_selection_info_resources_training_material_aid_items')
    op.drop_index('ix_csi_res_simulator_type_resources_id', table_name='course_selection_info_resources_simulator_type_items')
    op.drop_table('course_selection_info_resources_simulator_type_items')
    op.drop_index('ix_csi_res_personal_flight_eq_resources_id', table_name='course_selection_info_resources_personal_flight_equipment_items')
    op.drop_table('course_selection_info_resources_personal_flight_equipment_items')
    op.drop_index('ix_csi_res_mission_plan_sys_resources_id', table_name='course_selection_info_resources_mission_planning_system_items')
    op.drop_table('course_selection_info_resources_mission_planning_system_items')
    op.drop_index('ix_csi_res_ground_maint_resources_id', table_name='course_selection_info_resources_ground_maintenance_items')
    op.drop_table('course_selection_info_resources_ground_maintenance_items')
    op.drop_index('ix_csi_res_ground_armament_resources_id', table_name='course_selection_info_resources_ground_armament_items')
    op.drop_table('course_selection_info_resources_ground_armament_items')
    op.drop_index('ix_csi_res_classroom_req_resources_id', table_name='course_selection_info_resources_classroom_requirement_items')
    op.drop_table('course_selection_info_resources_classroom_requirement_items')
    op.drop_index('ix_csi_res_aviation_life_supp_resources_id', table_name='course_selection_info_resources_aviation_life_support_items')
    op.drop_table('course_selection_info_resources_aviation_life_support_items')
    op.drop_index('ix_csi_res_aircraft_resources_id', table_name='course_selection_info_resources_aircraft_items')
    op.drop_table('course_selection_info_resources_aircraft_items')
    op.drop_index('ix_csi_res_acft_armament_resources_id', table_name='course_selection_info_resources_aircraft_armament_items')
    op.drop_table('course_selection_info_resources_aircraft_armament_items')
    op.drop_index('ix_csi_res_acft_mission_eq_resources_id', table_name='course_selection_info_resources_acft_mission_equip_items')
    op.drop_table('course_selection_info_resources_acft_mission_equip_items')
    op.drop_index('ix_csi_lp_type_of_periods_lp_id', table_name='course_selection_info_lesson_planning_type_of_periods')
    op.drop_table('course_selection_info_lesson_planning_type_of_periods')
    op.drop_index('ix_csi_lp_training_objectives_lp_id', table_name='course_selection_info_lesson_planning_training_objectives')
    op.drop_table('course_selection_info_lesson_planning_training_objectives')
    op.drop_index('ix_csi_lp_teaching_points_lp_id', table_name='course_selection_info_lesson_planning_teaching_points')
    op.drop_table('course_selection_info_lesson_planning_teaching_points')
    op.drop_index('ix_csi_lp_environments_lp_id', table_name='course_selection_info_lesson_planning_environments')
    op.drop_table('course_selection_info_lesson_planning_environments')
    op.drop_index('ix_csi_lp_enabling_objectives_lp_id', table_name='course_selection_info_lesson_planning_enabling_objectives')
    op.drop_table('course_selection_info_lesson_planning_enabling_objectives')
    op.drop_index('ix_csi_lp_classif_of_periods_lp_id', table_name='course_selection_info_lesson_planning_classification_of_periods')
    op.drop_table('course_selection_info_lesson_planning_classification_of_periods')
    op.drop_index('ix_csi_lc_lessons_lesson_creation_id', table_name='course_selection_info_lesson_creation_lessons')
    op.drop_table('course_selection_info_lesson_creation_lessons')
    op.drop_index('ix_csi_instr_qual_req_personnel_id', table_name='course_selection_info_instructor_qualification_requirements')
    op.drop_index('ix_csi_instr_qual_req_master_id', table_name='course_selection_info_instructor_qualification_requirements')
    op.drop_table('course_selection_info_instructor_qualification_requirements')
    op.drop_index('ix_csi_entry_std_master_id', table_name='course_selection_info_entry_standards')
    op.drop_index('ix_csi_entry_std_general_id', table_name='course_selection_info_entry_standards')
    op.drop_table('course_selection_info_entry_standards')
    op.drop_index(op.f('ix_course_selection_info_resources_course_instance_id'), table_name='course_selection_info_resources')
    op.drop_table('course_selection_info_resources')
    op.drop_index('ix_csi_personnel_req_instance_id', table_name='course_selection_info_personnel_requirement')
    op.drop_table('course_selection_info_personnel_requirement')
    op.drop_index(op.f('ix_course_selection_info_lesson_planning_course_instance_id'), table_name='course_selection_info_lesson_planning')
    op.drop_table('course_selection_info_lesson_planning')
    op.drop_index(op.f('ix_course_selection_info_lesson_creation_course_instance_id'), table_name='course_selection_info_lesson_creation')
    op.drop_table('course_selection_info_lesson_creation')
    op.drop_index(op.f('ix_course_selection_info_general_course_instance_id'), table_name='course_selection_info_general')
    op.drop_table('course_selection_info_general')
    # ### end Alembic commands ###
