"""Update Index for RAG and analytics

Revision ID: 75a3b917a1bb
Revises: b1c2d3e4f5a6
Create Date: 2026-07-09 09:20:28.956907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a3b917a1bb'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concurrency_snapshots_bucket_ts'), table_name='concurrency_snapshots')
    op.create_index('ix_concurrency_snapshots_bucket_ts', 'concurrency_snapshots', ['bucket_ts'], unique=False)
    op.create_unique_constraint('uq_concurrency_snapshots_bucket_ts', 'concurrency_snapshots', ['bucket_ts'])
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_document_chunks_tsv_gin'), table_name='document_chunks', postgresql_using='gin')
    op.create_index('ix_usage_events_ip_ts', 'usage_events', ['ip', 'timestamp'], unique=False)
    op.create_index('ix_usage_events_user_ts', 'usage_events', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_user_ts', table_name='usage_events')
    op.drop_index('ix_usage_events_ip_ts', table_name='usage_events')
    op.create_index(op.f('ix_document_chunks_tsv_gin'), 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint('uq_concurrency_snapshots_bucket_ts', 'concurrency_snapshots', type_='unique')
    op.drop_index('ix_concurrency_snapshots_bucket_ts', table_name='concurrency_snapshots')
    op.create_index(op.f('ix_concurrency_snapshots_bucket_ts'), 'concurrency_snapshots', ['bucket_ts'], unique=True)
    # ### end Alembic commands ###
