"""add virtual class room feature

Revision ID: 75dd7635fc9f
Revises: 6719f7bab0fe
Create Date: 2026-05-13 08:53:30.626959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75dd7635fc9f'
down_revision: Union[str, None] = '6719f7bab0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('livekit_room_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('parent_session_id', sa.Integer(), nullable=True),
    sa.Column('participant_user_ids', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED')", name='ck_class_session_status'),
    sa.CheckConstraint('max_participants > 0 AND max_participants <= 200', name='ck_class_session_max_participants'),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_class_session_time_order'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livekit_room_name')
    )
    op.create_index(op.f('ix_class_sessions_host_user_id'), 'class_sessions', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_parent_session_id'), 'class_sessions', ['parent_session_id'], unique=False)
    op.create_table('class_session_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('egress_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('STARTING', 'ACTIVE', 'FINISHED', 'FAILED', 'ABORTED')", name='ck_class_session_recording_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_session_recordings_egress_id'), 'class_session_recordings', ['egress_id'], unique=True)
    op.create_index(op.f('ix_class_session_recordings_session_id'), 'class_session_recordings', ['session_id'], unique=False)
    #op.drop_index(op.f('ix_audit_logs_table_row'), table_name='audit_logs')
    #op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    #op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    #op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    #op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.alter_column('quizzes', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    #op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('quizzes', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_row'), 'audit_logs', ['table_name', 'row_id'], unique=False)
    op.drop_index(op.f('ix_class_session_recordings_session_id'), table_name='class_session_recordings')
    op.drop_index(op.f('ix_class_session_recordings_egress_id'), table_name='class_session_recordings')
    op.drop_table('class_session_recordings')
    op.drop_index(op.f('ix_class_sessions_parent_session_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_host_user_id'), table_name='class_sessions')
    op.drop_table('class_sessions')
    # ### end Alembic commands ###
