"""Introduce AIRF, Experience, Currency and Platform tables

Revision ID: 8cb15abeb022
Revises: 04fcd61bc533
Create Date: 2026-05-11 14:22:16.331511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb15abeb022'
down_revision: Union[str, None] = '04fcd61bc533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_airf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('blocking_status', sa.String(length=20), nullable=True),
    sa.Column('no_go_status', sa.String(length=20), nullable=True),
    sa.Column('go_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_fitnesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('iso_prep', sa.String(length=20), nullable=False),
    sa.Column('limitation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('profile_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('platform_code', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_airf_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airf_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=510), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('read_on_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airf_id'], ['profile_airf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_currency_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('last_performed', sa.Date(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('extended_to', sa.Date(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['profile_currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profile_fitness')
    op.add_column('profiles', sa.Column('qualification', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'qualification')
    op.create_table('profile_fitness',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('isoprep_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('limitation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_fitness_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_fitness_pkey')),
    sa.UniqueConstraint('profile_id', name=op.f('profile_fitness_profile_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('profile_currency_items')
    op.drop_table('profile_airf_items')
    op.drop_table('profile_platforms')
    op.drop_table('profile_fitnesses')
    op.drop_table('profile_experiences')
    op.drop_table('profile_currencies')
    op.drop_table('profile_airf')
    # ### end Alembic commands ###
