"""Add Index chat_message_reactions

Revision ID: 951b171778c7
Revises: 2dabb219ac51
Create Date: 2026-07-13 12:02:59.832228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951b171778c7'
down_revision: Union[str, None] = '2dabb219ac51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_reactions_message_id'), table_name='chat_message_reactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_message_reactions_message_id'), 'chat_message_reactions', ['message_id'], unique=False)
    # ### end Alembic commands ###
