"""Introduce Country table

Revision ID: 966324808b78
Revises: 03e943e92e0d
Create Date: 2026-05-20 11:48:23.364191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966324808b78'
down_revision: Union[str, None] = '03e943e92e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    # ### end Alembic commands ###

    op.execute("""
INSERT INTO countries(name) VALUES('AFGHANISTAN');
INSERT INTO countries(name) VALUES('ALBANIA');
INSERT INTO countries(name) VALUES('ALGERIA');
INSERT INTO countries(name) VALUES('AMERICAN SAMOA');
INSERT INTO countries(name) VALUES('ANDORRA');
INSERT INTO countries(name) VALUES('ANGOLA');
INSERT INTO countries(name) VALUES('ANGUILLA');
INSERT INTO countries(name) VALUES('ANTARCTICA');
INSERT INTO countries(name) VALUES('ANTIGUA AND BARBUDA');
INSERT INTO countries(name) VALUES('ARGENTINA');
INSERT INTO countries(name) VALUES('ARMENIA');
INSERT INTO countries(name) VALUES('ARUBA');
INSERT INTO countries(name) VALUES('AUSTRALIA');
INSERT INTO countries(name) VALUES('AUSTRIA');
INSERT INTO countries(name) VALUES('AZERBAIJAN');
INSERT INTO countries(name) VALUES('BAHAMAS');
INSERT INTO countries(name) VALUES('BAHRAIN');
INSERT INTO countries(name) VALUES('BANGLADESH');
INSERT INTO countries(name) VALUES('BARBADOS');
INSERT INTO countries(name) VALUES('BELARUS');
INSERT INTO countries(name) VALUES('BELGIUM');
INSERT INTO countries(name) VALUES('BELIZE');
INSERT INTO countries(name) VALUES('BENIN');
INSERT INTO countries(name) VALUES('BERMUDA');
INSERT INTO countries(name) VALUES('BHUTAN');
INSERT INTO countries(name) VALUES('BOLIVIA');
INSERT INTO countries(name) VALUES('BONAIRE');
INSERT INTO countries(name) VALUES('BOSNIA AND HERZEGOVINA');
INSERT INTO countries(name) VALUES('BOTSWANA');
INSERT INTO countries(name) VALUES('BOUVET ISLAND');
INSERT INTO countries(name) VALUES('BRASIL');
INSERT INTO countries(name) VALUES('BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO countries(name) VALUES('BRUNEI');
INSERT INTO countries(name) VALUES('BULGARIA');
INSERT INTO countries(name) VALUES('BURKINA FASO');
INSERT INTO countries(name) VALUES('BURUNDI');
INSERT INTO countries(name) VALUES('CAMBODIA');
INSERT INTO countries(name) VALUES('CAMEROON');
INSERT INTO countries(name) VALUES('CANADA');
INSERT INTO countries(name) VALUES('CAPE VERDE');
INSERT INTO countries(name) VALUES('CAYMAN ISLANDS');
INSERT INTO countries(name) VALUES('CENTRAL AFRICAN REPUBLIC');
INSERT INTO countries(name) VALUES('CHAD');
INSERT INTO countries(name) VALUES('CHILE');
INSERT INTO countries(name) VALUES('CHINA');
INSERT INTO countries(name) VALUES('CHRISTMAS ISLAND');
INSERT INTO countries(name) VALUES('COCOS (KEELING) ISLANDS');
INSERT INTO countries(name) VALUES('COLOMBIA');
INSERT INTO countries(name) VALUES('COMOROS');
INSERT INTO countries(name) VALUES('CONGO');
INSERT INTO countries(name) VALUES('DEMOCRATIC REPUBLIC OF THE CONGO');
INSERT INTO countries(name) VALUES('COOK ISLANDS');
INSERT INTO countries(name) VALUES('COSTA RICA');
INSERT INTO countries(name) VALUES('CROATIA');
INSERT INTO countries(name) VALUES('CUBA');
INSERT INTO countries(name) VALUES('CURACAO');
INSERT INTO countries(name) VALUES('CYPRUS');
INSERT INTO countries(name) VALUES('CZECH REPUBLIC');
INSERT INTO countries(name) VALUES('COTE DIVOIRE');
INSERT INTO countries(name) VALUES('DENMARK');
INSERT INTO countries(name) VALUES('DJIBOUTI');
INSERT INTO countries(name) VALUES('DOMINICA');
INSERT INTO countries(name) VALUES('DOMINICAN REPUBLIC');
INSERT INTO countries(name) VALUES('ECUADOR');
INSERT INTO countries(name) VALUES('EGYPT');
INSERT INTO countries(name) VALUES('EL SALVADOR');
INSERT INTO countries(name) VALUES('EQUATORIAL GUINEA');
INSERT INTO countries(name) VALUES('ERITREA');
INSERT INTO countries(name) VALUES('ESTONIA');
INSERT INTO countries(name) VALUES('ETHIOPIA');
INSERT INTO countries(name) VALUES('FALKLAND ISLANDS/ISLAS MALVINAS');
INSERT INTO countries(name) VALUES('FAROE ISLANDS');
INSERT INTO countries(name) VALUES('FIJI');
INSERT INTO countries(name) VALUES('FINLAND');
INSERT INTO countries(name) VALUES('FRANCE');
INSERT INTO countries(name) VALUES('FRENCH GUIANA');
INSERT INTO countries(name) VALUES('FRENCH POLYNESIA');
INSERT INTO countries(name) VALUES('FRENCH SOUTHERN TERRITORIES');
INSERT INTO countries(name) VALUES('GABON');
INSERT INTO countries(name) VALUES('GAMBIA');
INSERT INTO countries(name) VALUES('GEORGIA');
INSERT INTO countries(name) VALUES('GERMANY');
INSERT INTO countries(name) VALUES('GHANA');
INSERT INTO countries(name) VALUES('GIBRALTAR');
INSERT INTO countries(name) VALUES('GREECE');
INSERT INTO countries(name) VALUES('GREENLAND');
INSERT INTO countries(name) VALUES('GRENADA');
INSERT INTO countries(name) VALUES('GUADELOUPE');
INSERT INTO countries(name) VALUES('GUAM');
INSERT INTO countries(name) VALUES('GUATEMALA');
INSERT INTO countries(name) VALUES('GUERNSEY');
INSERT INTO countries(name) VALUES('GUINEA');
INSERT INTO countries(name) VALUES('GUINEA-BISSAU');
INSERT INTO countries(name) VALUES('GUYANA');
INSERT INTO countries(name) VALUES('HAITI');
INSERT INTO countries(name) VALUES('HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO countries(name) VALUES('HONDURAS');
INSERT INTO countries(name) VALUES('HONG KONG');
INSERT INTO countries(name) VALUES('HUNGARY');
INSERT INTO countries(name) VALUES('ICELAND');
INSERT INTO countries(name) VALUES('INDIA');
INSERT INTO countries(name) VALUES('INDONESIA');
INSERT INTO countries(name) VALUES('IRAN');
INSERT INTO countries(name) VALUES('IRAQ');
INSERT INTO countries(name) VALUES('IRELAND');
INSERT INTO countries(name) VALUES('ISLE OF MAN');
INSERT INTO countries(name) VALUES('ISRAEL');
INSERT INTO countries(name) VALUES('ITALY');
INSERT INTO countries(name) VALUES('JAMAICA');
INSERT INTO countries(name) VALUES('JAPAN');
INSERT INTO countries(name) VALUES('JERSEY');
INSERT INTO countries(name) VALUES('JORDAN');
INSERT INTO countries(name) VALUES('KAZAKHSTAN');
INSERT INTO countries(name) VALUES('KENYA');
INSERT INTO countries(name) VALUES('KIRIBATI');
INSERT INTO countries(name) VALUES('NORTH KOREA');
INSERT INTO countries(name) VALUES('SOUTH KOREA');
INSERT INTO countries(name) VALUES('KUWAIT');
INSERT INTO countries(name) VALUES('KYRGYZSTAN');
INSERT INTO countries(name) VALUES('LAOS');
INSERT INTO countries(name) VALUES('LATVIA');
INSERT INTO countries(name) VALUES('LEBANON');
INSERT INTO countries(name) VALUES('LESOTHO');
INSERT INTO countries(name) VALUES('LIBERIA');
INSERT INTO countries(name) VALUES('LIBYA');
INSERT INTO countries(name) VALUES('LIECHTENSTEIN');
INSERT INTO countries(name) VALUES('LITHUANIA');
INSERT INTO countries(name) VALUES('LUXEMBOURG');
INSERT INTO countries(name) VALUES('MACAU');
INSERT INTO countries(name) VALUES('MACEDONIA');
INSERT INTO countries(name) VALUES('MADAGASCAR');
INSERT INTO countries(name) VALUES('MALAWI');
INSERT INTO countries(name) VALUES('MALAYSIA');
INSERT INTO countries(name) VALUES('MALDIVES');
INSERT INTO countries(name) VALUES('MALI');
INSERT INTO countries(name) VALUES('MALTA');
INSERT INTO countries(name) VALUES('MARSHALL ISLANDS');
INSERT INTO countries(name) VALUES('MARTINIQUE');
INSERT INTO countries(name) VALUES('MAURITANIA');
INSERT INTO countries(name) VALUES('MAURITIUS');
INSERT INTO countries(name) VALUES('MAYOTTE');
INSERT INTO countries(name) VALUES('MEXICO');
INSERT INTO countries(name) VALUES('MICRONESIA');
INSERT INTO countries(name) VALUES('MOLDOVA');
INSERT INTO countries(name) VALUES('MONACO');
INSERT INTO countries(name) VALUES('MONGOLIA');
INSERT INTO countries(name) VALUES('MONTENEGRO');
INSERT INTO countries(name) VALUES('MONTSERRAT');
INSERT INTO countries(name) VALUES('MOROCCO');
INSERT INTO countries(name) VALUES('MOZAMBIQUE');
INSERT INTO countries(name) VALUES('MYANMAR');
INSERT INTO countries(name) VALUES('NAMIBIA');
INSERT INTO countries(name) VALUES('NAURU');
INSERT INTO countries(name) VALUES('NEPAL');
INSERT INTO countries(name) VALUES('NETHERLANDS');
INSERT INTO countries(name) VALUES('NEW CALEDONIA');
INSERT INTO countries(name) VALUES('NEW ZEALAND');
INSERT INTO countries(name) VALUES('NICARAGUA');
INSERT INTO countries(name) VALUES('NIGER');
INSERT INTO countries(name) VALUES('NIGERIA');
INSERT INTO countries(name) VALUES('NIUE');
INSERT INTO countries(name) VALUES('NORFOLK ISLAND');
INSERT INTO countries(name) VALUES('NORTHERN MARIANA ISLANDS');
INSERT INTO countries(name) VALUES('NORWAY');
INSERT INTO countries(name) VALUES('OMAN');
INSERT INTO countries(name) VALUES('PAKISTAN');
INSERT INTO countries(name) VALUES('PALAU');
INSERT INTO countries(name) VALUES('PALESTINE');
INSERT INTO countries(name) VALUES('PANAMA');
INSERT INTO countries(name) VALUES('PAPUA NEW GUINEA');
INSERT INTO countries(name) VALUES('PARAGUAY');
INSERT INTO countries(name) VALUES('PERU');
INSERT INTO countries(name) VALUES('PHILIPPINES');
INSERT INTO countries(name) VALUES('PITCAIRN ISLANDS');
INSERT INTO countries(name) VALUES('POLAND');
INSERT INTO countries(name) VALUES('PORTUGAL');
INSERT INTO countries(name) VALUES('PUERTO RICO');
INSERT INTO countries(name) VALUES('QATAR');
INSERT INTO countries(name) VALUES('ROMANIA');
INSERT INTO countries(name) VALUES('RUSSIA');
INSERT INTO countries(name) VALUES('RWANDA');
INSERT INTO countries(name) VALUES('RÉUNION');
INSERT INTO countries(name) VALUES('SAINT BARTHELEMY');
INSERT INTO countries(name) VALUES('SAINT HELENA');
INSERT INTO countries(name) VALUES('SAINT KITTS AND NEVIS');
INSERT INTO countries(name) VALUES('SAINT LUCIA');
INSERT INTO countries(name) VALUES('SAINT MARTIN');
INSERT INTO countries(name) VALUES('SAINT PIERRE AND MIQUELON');
INSERT INTO countries(name) VALUES('SAINT VINCENT AND THE GRENADINES');
INSERT INTO countries(name) VALUES('SAMOA');
INSERT INTO countries(name) VALUES('SAN MARINO');
INSERT INTO countries(name) VALUES('SAO TOME AND PRINCIPE');
INSERT INTO countries(name) VALUES('SAUDI ARABIA');
INSERT INTO countries(name) VALUES('SENEGAL');
INSERT INTO countries(name) VALUES('SERBIA');
INSERT INTO countries(name) VALUES('SEYCHELLES');
INSERT INTO countries(name) VALUES('SIERRA LEONE');
INSERT INTO countries(name) VALUES('SINGAPORE');
INSERT INTO countries(name) VALUES('SINT MAARTEN');
INSERT INTO countries(name) VALUES('SLOVAKIA');
INSERT INTO countries(name) VALUES('SLOVENIA');
INSERT INTO countries(name) VALUES('SOLOMON ISLANDS');
INSERT INTO countries(name) VALUES('SOMALIA');
INSERT INTO countries(name) VALUES('SOUTH AFRICA');
INSERT INTO countries(name) VALUES('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO countries(name) VALUES('SOUTH SUDAN');
INSERT INTO countries(name) VALUES('SPAIN');
INSERT INTO countries(name) VALUES('SRI LANKA');
INSERT INTO countries(name) VALUES('SUDAN');
INSERT INTO countries(name) VALUES('SURINAME');
INSERT INTO countries(name) VALUES('SVALBARD');
INSERT INTO countries(name) VALUES('SWAZILAND');
INSERT INTO countries(name) VALUES('SWEDEN');
INSERT INTO countries(name) VALUES('SWITZERLAND');
INSERT INTO countries(name) VALUES('SYRIA');
INSERT INTO countries(name) VALUES('REPUBLIC OF CHINA TAIWAN');
INSERT INTO countries(name) VALUES('TAJIKISTAN');
INSERT INTO countries(name) VALUES('TANZANIA');
INSERT INTO countries(name) VALUES('THAILAND');
INSERT INTO countries(name) VALUES('TIMOR-LESTE');
INSERT INTO countries(name) VALUES('TOGO');
INSERT INTO countries(name) VALUES('TOKELAU');
INSERT INTO countries(name) VALUES('TONGA');
INSERT INTO countries(name) VALUES('TRINIDAD AND TOBAGO');
INSERT INTO countries(name) VALUES('TUNISIA');
INSERT INTO countries(name) VALUES('TURKEY');
INSERT INTO countries(name) VALUES('TURKMENISTAN');
INSERT INTO countries(name) VALUES('TURKS AND CAICOS ISLANDS');
INSERT INTO countries(name) VALUES('TUVALU');
INSERT INTO countries(name) VALUES('UGANDA');
INSERT INTO countries(name) VALUES('UKRAINE');
INSERT INTO countries(name) VALUES('UNITED ARAB EMIRATES');
INSERT INTO countries(name) VALUES('UNITED KINGDOM');
INSERT INTO countries(name) VALUES('USA');
INSERT INTO countries(name) VALUES('URUGUAY');
INSERT INTO countries(name) VALUES('UZBEKISTAN');
INSERT INTO countries(name) VALUES('VANUATU');
INSERT INTO countries(name) VALUES('VENEZUELA');
INSERT INTO countries(name) VALUES('VIETNAM');
INSERT INTO countries(name) VALUES('BRITISH VIRGIN ISLANDS');
INSERT INTO countries(name) VALUES('U.S. VIRGIN ISLANDS');
INSERT INTO countries(name) VALUES('VATICAN CITY');
INSERT INTO countries(name) VALUES('WALLIS AND FUTUNA');
INSERT INTO countries(name) VALUES('WESTERN SAHARA');
INSERT INTO countries(name) VALUES('YEMEN');
INSERT INTO countries(name) VALUES('ZAMBIA');
               """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_table('countries')
    # ### end Alembic commands ###
