"""add_currencies_certificate_tables

Revision ID: 976d2a98395a
Revises: 020feca81dfb
Create Date: 2026-06-16 11:43:51.264544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976d2a98395a'
down_revision: Union[str, None] = '020feca81dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='green', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_master_code'), 'currencies_master', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_master_name'), 'currencies_master', ['name'], unique=True)
    op.create_table('master_course_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_master_id', sa.Integer(), nullable=False),
    sa.Column('currency_master_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_master_id'], ['course_masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_master_id'], ['currencies_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_master_id', 'currency_master_id', name='uq_master_course_currency')
    )
    op.create_index(op.f('ix_master_course_currencies_course_master_id'), 'master_course_currencies', ['course_master_id'], unique=False)
    op.create_index(op.f('ix_master_course_currencies_currency_master_id'), 'master_course_currencies', ['currency_master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_course_currencies_currency_master_id'), table_name='master_course_currencies')
    op.drop_index(op.f('ix_master_course_currencies_course_master_id'), table_name='master_course_currencies')
    op.drop_table('master_course_currencies')
    op.drop_index(op.f('ix_currencies_master_name'), table_name='currencies_master')
    op.drop_index(op.f('ix_currencies_master_code'), table_name='currencies_master')
    op.drop_table('currencies_master')
    # ### end Alembic commands ###
