"""Introduce Course Selection Schedule

Revision ID: 9f58cc5f0087
Revises: 23b3e88ffe89
Create Date: 2026-06-25 07:15:58.408649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f58cc5f0087'
down_revision: Union[str, None] = '23b3e88ffe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_session_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_instance_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('off_weekdays', sa.String(length=50), nullable=True),
    sa.Column('holidays', sa.Text(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_id'], ['course_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_session_schedules_course_instance_id'), 'course_session_schedules', ['course_instance_id'], unique=True)
    op.create_table('course_session_schedule_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_session_schedule_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_session_schedule_id'], ['course_session_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_session_schedule_days_course_session_schedule_id'), 'course_session_schedule_days', ['course_session_schedule_id'], unique=False)
    op.create_table('course_session_schedule_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_session_schedule_day_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('start_col', sa.Integer(), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_session_schedule_day_id'], ['course_session_schedule_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_selection_info_lesson_creation_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_session_schedule_placements_course_session_schedule_day_id'), 'course_session_schedule_placements', ['course_session_schedule_day_id'], unique=False)
    op.create_index(op.f('ix_course_session_schedule_placements_lesson_id'), 'course_session_schedule_placements', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_session_schedule_placements_lesson_id'), table_name='course_session_schedule_placements')
    op.drop_index(op.f('ix_course_session_schedule_placements_course_session_schedule_day_id'), table_name='course_session_schedule_placements')
    op.drop_table('course_session_schedule_placements')
    op.drop_index(op.f('ix_course_session_schedule_days_course_session_schedule_id'), table_name='course_session_schedule_days')
    op.drop_table('course_session_schedule_days')
    op.drop_index(op.f('ix_course_session_schedules_course_instance_id'), table_name='course_session_schedules')
    op.drop_table('course_session_schedules')
    # ### end Alembic commands ###
