"""Added date, student_id, lesson_id unique

Revision ID: a3f497962ba9
Revises: e59e429b0f94
Create Date: 2026-06-25 06:43:59.968873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f497962ba9'
down_revision: Union[str, None] = 'e59e429b0f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_record'), 'attendances', type_='unique')
    op.create_unique_constraint('uq_attendance_record', 'attendances', ['student_id', 'lesson_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_record', 'attendances', type_='unique')
    op.create_unique_constraint(op.f('uq_attendance_record'), 'attendances', ['student_id', 'date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
