"""add FAQ and IT Support

Revision ID: b2306ab3f629
Revises: 966324808b78
Create Date: 2026-06-01 07:56:32.762873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2306ab3f629'
down_revision: Union[str, None] = '966324808b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('it_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'approved', 'declined', 'viewed', 'resolved')", name='ck_it_tickets_status_valid'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_it_tickets_assigned_to_id'), 'it_tickets', ['assigned_to_id'], unique=False)
    op.create_index('ix_it_tickets_assigned_to_status', 'it_tickets', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_it_tickets_created_by_id'), 'it_tickets', ['created_by_id'], unique=False)
    op.create_index('ix_it_tickets_created_by_status', 'it_tickets', ['created_by_id', 'status'], unique=False)
    op.create_index(op.f('ix_it_tickets_status'), 'it_tickets', ['status'], unique=False)
    op.create_table('it_ticket_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('forwarded_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forwarded_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['it_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_it_ticket_history_ticket_id'), 'it_ticket_history', ['ticket_id'], unique=False)
    #op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_it_ticket_history_ticket_id'), table_name='it_ticket_history')
    op.drop_table('it_ticket_history')
    op.drop_index(op.f('ix_it_tickets_status'), table_name='it_tickets')
    op.drop_index('ix_it_tickets_created_by_status', table_name='it_tickets')
    op.drop_index(op.f('ix_it_tickets_created_by_id'), table_name='it_tickets')
    op.drop_index('ix_it_tickets_assigned_to_status', table_name='it_tickets')
    op.drop_index(op.f('ix_it_tickets_assigned_to_id'), table_name='it_tickets')
    op.drop_table('it_tickets')
    op.drop_table('faqs')
    # ### end Alembic commands ###
