"""introduce_library_material_summaries

Revision ID: c7f610e503b8
Revises: e701d8615662
Create Date: 2026-06-19 06:31:28.664134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f610e503b8'
# down_revision: Union[str, None] = 'e701d8615662'
down_revision: Union[str, None] = 'c6d7e8f9a0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_material_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_voice', sa.String(), nullable=True),
    sa.Column('mindmap', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['library_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_material_summaries_id'), 'library_material_summaries', ['id'], unique=True)
    # op.add_column('attendances', sa.Column('user_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'attendances', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    # op.drop_constraint(None, 'attendances', type_='foreignkey')
    # op.drop_column('attendances', 'user_id')
    op.drop_index(op.f('ix_library_material_summaries_id'), table_name='library_material_summaries')
    op.drop_table('library_material_summaries')
    # ### end Alembic commands ###
