"""Introduce Profile and ProfileFitness

Revision ID: cf3807113c3a
Revises: 1dcbc08b31db
Create Date: 2026-05-08 10:26:50.713941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf3807113c3a'
down_revision: Union[str, None] = '1dcbc08b31db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mobile_no', sa.String(length=50), nullable=True),
    sa.Column('ext_no', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('command', sa.String(length=20), nullable=True),
    sa.Column('esnaad_sync_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_fitness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('isoprep_status', sa.String(length=20), nullable=False),
    sa.Column('limitation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.drop_index(op.f('ix_audit_logs_table_row'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###

    op.execute(r"""
    INSERT INTO profiles(user_id,email,first_name,last_name,middle_name,rank,VERSION,created_at,updated_at)
    SELECT 
    id,
    email,
    split_part(clean_full_name, ' ', 1) AS first,
    CASE 
        WHEN position(' ' IN clean_full_name) = 0 THEN NULL 
        ELSE reverse(split_part(reverse(clean_full_name), ' ', 1)) 
    END AS last,
    CASE 
        WHEN position(' ' IN clean_full_name) = 0 THEN NULL
        WHEN position(' ' IN substring(clean_full_name FROM position(' ' IN clean_full_name) + 1)) = 0 THEN NULL
        ELSE trim(regexp_replace(clean_full_name, '^\S+\s+|\s+\S+$', ''))
    END AS middle
    , 'CIVILIAN' AS rank
    , 1 AS version
    , CURRENT_TIMESTAMP
    , current_timestamp  
    FROM (
    SELECT id, trim(regexp_replace(full_name, '\s+', ' ', 'g')) AS clean_full_name, email
    FROM users
    WHERE full_name IS NOT NULL AND trim(full_name) <> ''
    ) sub
               """)


def downgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN auth_provider TYPE authprovider USING auth_provider::authprovider")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EMAIL', 'LDAP', name='authprovider'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_row'), 'audit_logs', ['table_name', 'row_id'], unique=False)
    op.drop_table('profile_fitness')
    op.drop_table('profiles')
    # ### end Alembic commands ###
