"""Library reading progress

Revision ID: cfe3ac278d25
Revises: p1u2n3i4t5p6
Create Date: 2026-06-17 10:15:13.210593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe3ac278d25'
down_revision: Union[str, None] = 'p1u2n3i4t5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_material_user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['library_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_material_user_progress_material_id'), 'library_material_user_progress', ['material_id'], unique=False)
    op.create_index(op.f('ix_library_material_user_progress_user_id'), 'library_material_user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_material_user_progress_user_id'), table_name='library_material_user_progress')
    op.drop_index(op.f('ix_library_material_user_progress_material_id'), table_name='library_material_user_progress')
    op.drop_table('library_material_user_progress')
    # ### end Alembic commands ###
