"""Add lesson_id to attendance and remove section_id

Revision ID: e59e429b0f94
Revises: 9f58cc5f0087
Create Date: 2026-06-24 12:01:42.122576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59e429b0f94'
down_revision: Union[str, None] = '9f58cc5f0087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_attendance_record'), 'attendances', type_='unique')
    op.create_unique_constraint('uq_attendance_record', 'attendances', ['student_id', 'date'])
    op.drop_constraint(op.f('attendances_section_id_fkey'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'course_selection_info_lesson_creation_lessons', ['lesson_id'], ['id'])
    op.drop_column('attendances', 'section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_section_id_fkey'), 'attendances', 'sections', ['section_id'], ['id'])
    op.drop_constraint('uq_attendance_record', 'attendances', type_='unique')
    op.create_unique_constraint(op.f('uq_attendance_record'), 'attendances', ['student_id', 'section_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendances', 'lesson_id')
    # ### end Alembic commands ###
