"""add library model

Revision ID: e701d8615662
Revises: 19ff422c3cfe
Create Date: 2026-06-09 10:50:48.343923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e701d8615662'
down_revision: Union[str, None] = '19ff422c3cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=120), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=260), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('material_type', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('folder', sa.String(length=220), nullable=False),
    sa.Column('uploaded_by', sa.String(length=220), nullable=True),
    sa.Column('approved_status', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_constraint(op.f('uq_chat_messages_id'), 'chat_messages', type_='unique')
    op.drop_index(op.f('ix_course_info_entry_standards_general_id'), table_name='course_info_entry_standards')
    op.create_index(op.f('ix_course_info_entry_standards_course_entry_standard_id'), 'course_info_entry_standards', ['course_entry_standard_id'], unique=False)
    op.create_index(op.f('ix_course_info_entry_standards_course_info_general_id'), 'course_info_entry_standards', ['course_info_general_id'], unique=False)
    op.drop_column('course_info_entry_standards', 'created_at')
    op.drop_column('course_info_entry_standards', 'updated_at')
    op.drop_constraint(op.f('uq_course_info_general_course_info_id'), 'course_info_general', type_='unique')
    op.drop_index(op.f('ix_course_info_general_course_info_id'), table_name='course_info_general')
    op.create_index(op.f('ix_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], unique=True)
    op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_pr_id'), table_name='course_info_instructor_qualification_requirements')
    op.create_index(op.f('ix_course_info_instructor_qualification_requirements_course_info_personnel_requirement_id'), 'course_info_instructor_qualification_requirements', ['course_info_personnel_requirement_id'], unique=False)
    op.create_index(op.f('ix_course_info_instructor_qualification_requirements_instructor_qualification_requirement_id'), 'course_info_instructor_qualification_requirements', ['instructor_qualification_requirement_id'], unique=False)
    op.drop_column('course_info_instructor_qualification_requirements', 'created_at')
    op.drop_column('course_info_instructor_qualification_requirements', 'updated_at')
    op.drop_constraint(op.f('uq_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', type_='unique')
    op.drop_index(op.f('ix_course_info_lesson_creation_course_info_id'), table_name='course_info_lesson_creation')
    op.create_index(op.f('ix_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], unique=True)
    op.drop_index(op.f('ix_course_info_lesson_creation_lesson_units_lesson_id'), table_name='course_info_lesson_creation_lesson_units')
    op.create_index(op.f('ix_course_info_lesson_creation_lesson_units_course_info_lesson_creation_lesson_id'), 'course_info_lesson_creation_lesson_units', ['course_info_lesson_creation_lesson_id'], unique=False)
    op.drop_column('course_info_lesson_creation_lesson_units', 'created_at')
    op.drop_column('course_info_lesson_creation_lesson_units', 'updated_at')
    op.drop_index(op.f('ix_course_info_lesson_creation_lessons_parent_id'), table_name='course_info_lesson_creation_lessons')
    op.create_index(op.f('ix_course_info_lesson_creation_lessons_course_info_lesson_creation_id'), 'course_info_lesson_creation_lessons', ['course_info_lesson_creation_id'], unique=False)
    op.drop_column('course_info_lesson_creation_lessons', 'created_at')
    op.drop_column('course_info_lesson_creation_lessons', 'updated_at')
    op.drop_constraint(op.f('uq_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', type_='unique')
    op.drop_index(op.f('ix_course_info_lesson_planning_course_info_id'), table_name='course_info_lesson_planning')
    op.create_index(op.f('ix_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], unique=True)
    op.drop_index(op.f('ix_cilp_classification_of_periods_lp_id'), table_name='course_info_lesson_planning_classification_of_periods')
    op.create_index(op.f('ix_course_info_lesson_planning_classification_of_periods_course_info_lesson_planning_id'), 'course_info_lesson_planning_classification_of_periods', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_cilp_enabling_objectives_lp_id'), table_name='course_info_lesson_planning_enabling_objectives')
    op.create_index(op.f('ix_course_info_lesson_planning_enabling_objectives_course_info_lesson_planning_id'), 'course_info_lesson_planning_enabling_objectives', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_cilp_environments_lp_id'), table_name='course_info_lesson_planning_environments')
    op.create_index(op.f('ix_course_info_lesson_planning_environments_course_info_lesson_planning_id'), 'course_info_lesson_planning_environments', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_cilp_teaching_points_lp_id'), table_name='course_info_lesson_planning_teaching_points')
    op.create_index(op.f('ix_course_info_lesson_planning_teaching_points_course_info_lesson_planning_id'), 'course_info_lesson_planning_teaching_points', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_cilp_training_objectives_lp_id'), table_name='course_info_lesson_planning_training_objectives')
    op.create_index(op.f('ix_course_info_lesson_planning_training_objectives_course_info_lesson_planning_id'), 'course_info_lesson_planning_training_objectives', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_cilp_type_of_periods_lp_id'), table_name='course_info_lesson_planning_type_of_periods')
    op.create_index(op.f('ix_course_info_lesson_planning_type_of_periods_course_info_lesson_planning_id'), 'course_info_lesson_planning_type_of_periods', ['course_info_lesson_planning_id'], unique=False)
    op.drop_constraint(op.f('uq_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', type_='unique')
    op.drop_index(op.f('ix_course_info_personnel_requirement_course_info_id'), table_name='course_info_personnel_requirement')
    op.create_index(op.f('ix_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], unique=True)
    op.drop_constraint(op.f('uq_course_info_resources_course_info_id'), 'course_info_resources', type_='unique')
    op.drop_index(op.f('ix_course_info_resources_course_info_id'), table_name='course_info_resources')
    op.create_index(op.f('ix_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], unique=True)
    op.drop_index(op.f('ix_cir_aircraft_armament_res_id'), table_name='course_info_resources_aircraft_armament_items')
    op.create_index(op.f('ix_course_info_resources_aircraft_armament_items_course_info_resources_id'), 'course_info_resources_aircraft_armament_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_aircraft_items_resources_id'), table_name='course_info_resources_aircraft_items')
    op.create_index(op.f('ix_course_info_resources_aircraft_items_course_info_resources_id'), 'course_info_resources_aircraft_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_aircraft_mission_equip_res_id'), table_name='course_info_resources_aircraft_mission_equipment_items')
    op.create_index(op.f('ix_course_info_resources_aircraft_mission_equipment_items_course_info_resources_id'), 'course_info_resources_aircraft_mission_equipment_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_aviation_life_support_res_id'), table_name='course_info_resources_aviation_life_support_items')
    op.create_index(op.f('ix_course_info_resources_aviation_life_support_items_course_info_resources_id'), 'course_info_resources_aviation_life_support_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_classroom_req_res_id'), table_name='course_info_resources_classroom_requirement_items')
    op.create_index(op.f('ix_course_info_resources_classroom_requirement_items_course_info_resources_id'), 'course_info_resources_classroom_requirement_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_ground_armament_res_id'), table_name='course_info_resources_ground_armament_items')
    op.create_index(op.f('ix_course_info_resources_ground_armament_items_course_info_resources_id'), 'course_info_resources_ground_armament_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_ground_maintenance_res_id'), table_name='course_info_resources_ground_maintenance_items')
    op.create_index(op.f('ix_course_info_resources_ground_maintenance_items_course_info_resources_id'), 'course_info_resources_ground_maintenance_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_mission_plan_sys_res_id'), table_name='course_info_resources_mission_planning_system_items')
    op.create_index(op.f('ix_course_info_resources_mission_planning_system_items_course_info_resources_id'), 'course_info_resources_mission_planning_system_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_personal_flight_equip_res_id'), table_name='course_info_resources_personal_flight_equipment_items')
    op.create_index(op.f('ix_course_info_resources_personal_flight_equipment_items_course_info_resources_id'), 'course_info_resources_personal_flight_equipment_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_simulator_type_res_id'), table_name='course_info_resources_simulator_type_items')
    op.create_index(op.f('ix_course_info_resources_simulator_type_items_course_info_resources_id'), 'course_info_resources_simulator_type_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_cir_training_material_aid_res_id'), table_name='course_info_resources_training_material_aid_items')
    op.create_index(op.f('ix_course_info_resources_training_material_aid_items_course_info_resources_id'), 'course_info_resources_training_material_aid_items', ['course_info_resources_id'], unique=False)
    op.drop_constraint(op.f('uq_course_infos_course_master_id'), 'course_infos', type_='unique')
    op.drop_index(op.f('ix_course_infos_course_master_id'), table_name='course_infos')
    op.create_index(op.f('ix_course_infos_course_master_id'), 'course_infos', ['course_master_id'], unique=True)
    op.drop_index(op.f('ix_course_instances_master_id'), table_name='course_instances')
    op.drop_index(op.f('ix_course_modification_requests_course_id'), table_name='course_modification_requests')
    op.drop_constraint(op.f('course_modification_requests_course_id_fkey'), 'course_modification_requests', type_='foreignkey')
    op.create_foreign_key(None, 'course_modification_requests', 'course_instances', ['course_id'], ['id'])
    op.drop_constraint(op.f('uq_course_schedules_course_master_id'), 'course_schedules', type_='unique')
    op.drop_index(op.f('ix_course_schedules_course_master_id'), table_name='course_schedules')
    op.create_index(op.f('ix_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], unique=True)
    op.drop_constraint(op.f('uq_evaluations_course_master_id'), 'evaluations', type_='unique')
    op.drop_index(op.f('ix_evaluations_course_master_id'), table_name='evaluations')
    op.create_index(op.f('ix_evaluations_course_master_id'), 'evaluations', ['course_master_id'], unique=True)
    op.drop_constraint(op.f('uq_form_builders_course_master_id'), 'form_builders', type_='unique')
    op.drop_index(op.f('ix_form_builders_course_master_id'), table_name='form_builders')
    op.create_index(op.f('ix_form_builders_course_master_id'), 'form_builders', ['course_master_id'], unique=True)
    op.drop_constraint(op.f('uq_materials_course_master_id'), 'materials', type_='unique')
    op.drop_index(op.f('ix_materials_course_master_id'), table_name='materials')
    op.create_index(op.f('ix_materials_course_master_id'), 'materials', ['course_master_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_course_master_id'), table_name='materials')
    op.create_index(op.f('ix_materials_course_master_id'), 'materials', ['course_master_id'], unique=False)
    op.create_unique_constraint(op.f('uq_materials_course_master_id'), 'materials', ['course_master_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_form_builders_course_master_id'), table_name='form_builders')
    op.create_index(op.f('ix_form_builders_course_master_id'), 'form_builders', ['course_master_id'], unique=False)
    op.create_unique_constraint(op.f('uq_form_builders_course_master_id'), 'form_builders', ['course_master_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_evaluations_course_master_id'), table_name='evaluations')
    op.create_index(op.f('ix_evaluations_course_master_id'), 'evaluations', ['course_master_id'], unique=False)
    op.create_unique_constraint(op.f('uq_evaluations_course_master_id'), 'evaluations', ['course_master_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_course_schedules_course_master_id'), table_name='course_schedules')
    op.create_index(op.f('ix_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_schedules_course_master_id'), 'course_schedules', ['course_master_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'course_modification_requests', type_='foreignkey')
    op.create_foreign_key(op.f('course_modification_requests_course_id_fkey'), 'course_modification_requests', 'course_instances', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_course_modification_requests_course_id'), 'course_modification_requests', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_instances_master_id'), 'course_instances', ['master_id'], unique=False)
    op.drop_index(op.f('ix_course_infos_course_master_id'), table_name='course_infos')
    op.create_index(op.f('ix_course_infos_course_master_id'), 'course_infos', ['course_master_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_infos_course_master_id'), 'course_infos', ['course_master_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_course_info_resources_training_material_aid_items_course_info_resources_id'), table_name='course_info_resources_training_material_aid_items')
    op.create_index(op.f('ix_cir_training_material_aid_res_id'), 'course_info_resources_training_material_aid_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_simulator_type_items_course_info_resources_id'), table_name='course_info_resources_simulator_type_items')
    op.create_index(op.f('ix_cir_simulator_type_res_id'), 'course_info_resources_simulator_type_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_personal_flight_equipment_items_course_info_resources_id'), table_name='course_info_resources_personal_flight_equipment_items')
    op.create_index(op.f('ix_cir_personal_flight_equip_res_id'), 'course_info_resources_personal_flight_equipment_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_mission_planning_system_items_course_info_resources_id'), table_name='course_info_resources_mission_planning_system_items')
    op.create_index(op.f('ix_cir_mission_plan_sys_res_id'), 'course_info_resources_mission_planning_system_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_ground_maintenance_items_course_info_resources_id'), table_name='course_info_resources_ground_maintenance_items')
    op.create_index(op.f('ix_cir_ground_maintenance_res_id'), 'course_info_resources_ground_maintenance_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_ground_armament_items_course_info_resources_id'), table_name='course_info_resources_ground_armament_items')
    op.create_index(op.f('ix_cir_ground_armament_res_id'), 'course_info_resources_ground_armament_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_classroom_requirement_items_course_info_resources_id'), table_name='course_info_resources_classroom_requirement_items')
    op.create_index(op.f('ix_cir_classroom_req_res_id'), 'course_info_resources_classroom_requirement_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_aviation_life_support_items_course_info_resources_id'), table_name='course_info_resources_aviation_life_support_items')
    op.create_index(op.f('ix_cir_aviation_life_support_res_id'), 'course_info_resources_aviation_life_support_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_aircraft_mission_equipment_items_course_info_resources_id'), table_name='course_info_resources_aircraft_mission_equipment_items')
    op.create_index(op.f('ix_cir_aircraft_mission_equip_res_id'), 'course_info_resources_aircraft_mission_equipment_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_aircraft_items_course_info_resources_id'), table_name='course_info_resources_aircraft_items')
    op.create_index(op.f('ix_course_info_resources_aircraft_items_resources_id'), 'course_info_resources_aircraft_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_aircraft_armament_items_course_info_resources_id'), table_name='course_info_resources_aircraft_armament_items')
    op.create_index(op.f('ix_cir_aircraft_armament_res_id'), 'course_info_resources_aircraft_armament_items', ['course_info_resources_id'], unique=False)
    op.drop_index(op.f('ix_course_info_resources_course_info_id'), table_name='course_info_resources')
    op.create_index(op.f('ix_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_info_resources_course_info_id'), 'course_info_resources', ['course_info_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_course_info_personnel_requirement_course_info_id'), table_name='course_info_personnel_requirement')
    op.create_index(op.f('ix_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_info_personnel_requirement_course_info_id'), 'course_info_personnel_requirement', ['course_info_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_type_of_periods_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_type_of_periods')
    op.create_index(op.f('ix_cilp_type_of_periods_lp_id'), 'course_info_lesson_planning_type_of_periods', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_training_objectives_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_training_objectives')
    op.create_index(op.f('ix_cilp_training_objectives_lp_id'), 'course_info_lesson_planning_training_objectives', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_teaching_points_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_teaching_points')
    op.create_index(op.f('ix_cilp_teaching_points_lp_id'), 'course_info_lesson_planning_teaching_points', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_environments_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_environments')
    op.create_index(op.f('ix_cilp_environments_lp_id'), 'course_info_lesson_planning_environments', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_enabling_objectives_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_enabling_objectives')
    op.create_index(op.f('ix_cilp_enabling_objectives_lp_id'), 'course_info_lesson_planning_enabling_objectives', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_classification_of_periods_course_info_lesson_planning_id'), table_name='course_info_lesson_planning_classification_of_periods')
    op.create_index(op.f('ix_cilp_classification_of_periods_lp_id'), 'course_info_lesson_planning_classification_of_periods', ['course_info_lesson_planning_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_planning_course_info_id'), table_name='course_info_lesson_planning')
    op.create_index(op.f('ix_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_info_lesson_planning_course_info_id'), 'course_info_lesson_planning', ['course_info_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_info_lesson_creation_lessons', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('course_info_lesson_creation_lessons', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_course_info_lesson_creation_lessons_course_info_lesson_creation_id'), table_name='course_info_lesson_creation_lessons')
    op.create_index(op.f('ix_course_info_lesson_creation_lessons_parent_id'), 'course_info_lesson_creation_lessons', ['course_info_lesson_creation_id'], unique=False)
    op.add_column('course_info_lesson_creation_lesson_units', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('course_info_lesson_creation_lesson_units', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_course_info_lesson_creation_lesson_units_course_info_lesson_creation_lesson_id'), table_name='course_info_lesson_creation_lesson_units')
    op.create_index(op.f('ix_course_info_lesson_creation_lesson_units_lesson_id'), 'course_info_lesson_creation_lesson_units', ['course_info_lesson_creation_lesson_id'], unique=False)
    op.drop_index(op.f('ix_course_info_lesson_creation_course_info_id'), table_name='course_info_lesson_creation')
    op.create_index(op.f('ix_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_info_lesson_creation_course_info_id'), 'course_info_lesson_creation', ['course_info_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_info_instructor_qualification_requirements', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('course_info_instructor_qualification_requirements', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_instructor_qualification_requirement_id'), table_name='course_info_instructor_qualification_requirements')
    op.drop_index(op.f('ix_course_info_instructor_qualification_requirements_course_info_personnel_requirement_id'), table_name='course_info_instructor_qualification_requirements')
    op.create_index(op.f('ix_course_info_instructor_qualification_requirements_pr_id'), 'course_info_instructor_qualification_requirements', ['course_info_personnel_requirement_id'], unique=False)
    op.drop_index(op.f('ix_course_info_general_course_info_id'), table_name='course_info_general')
    op.create_index(op.f('ix_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], unique=False)
    op.create_unique_constraint(op.f('uq_course_info_general_course_info_id'), 'course_info_general', ['course_info_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_info_entry_standards', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('course_info_entry_standards', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_course_info_entry_standards_course_info_general_id'), table_name='course_info_entry_standards')
    op.drop_index(op.f('ix_course_info_entry_standards_course_entry_standard_id'), table_name='course_info_entry_standards')
    op.create_index(op.f('ix_course_info_entry_standards_general_id'), 'course_info_entry_standards', ['course_info_general_id'], unique=False)
    op.create_unique_constraint(op.f('uq_chat_messages_id'), 'chat_messages', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_table('library_materials')
    # ### end Alembic commands ###
