"""Introduce RAG

Revision ID: f0a55b923726
Revises: u5a6g7e8v9a0
Create Date: 2026-07-06 10:04:44.478272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0a55b923726'
down_revision: Union[str, None] = 'm1f2a3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('rag_ingestion_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_rag_ingestion_source')
    )
    op.create_index(op.f('ix_rag_ingestion_state_source_id'), 'rag_ingestion_state', ['source_id'], unique=False)
    op.create_index(op.f('ix_rag_ingestion_state_source_type'), 'rag_ingestion_state', ['source_type'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('course_material_file_id', sa.UUID(), nullable=True),
    sa.Column('course_instance_id', sa.Integer(), nullable=True),
    sa.Column('library_material_id', sa.Integer(), nullable=True),
    sa.Column('document_title', sa.String(length=500), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=1024), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_material_file_id'], ['course_selection_material_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_material_id'], ['library_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_course_instance_id'), 'document_chunks', ['course_instance_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_course_material_file_id'), 'document_chunks', ['course_material_file_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_library_material_id'), 'document_chunks', ['library_material_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_type'), 'document_chunks', ['source_type'], unique=False)
    op.drop_constraint(op.f('uq_concurrency_snapshots_bucket_ts'), 'concurrency_snapshots', type_='unique')
    op.drop_index(op.f('ix_concurrency_snapshots_bucket_ts'), table_name='concurrency_snapshots')
    op.create_index(op.f('ix_concurrency_snapshots_bucket_ts'), 'concurrency_snapshots', ['bucket_ts'], unique=True)
    op.alter_column('flight_pack_fills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('flight_pack_fills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('flight_pack_grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('flight_pack_grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_usage_events_ip_ts'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_user_ts'), table_name='usage_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_events_user_ts'), 'usage_events', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_usage_events_ip_ts'), 'usage_events', ['ip', 'timestamp'], unique=False)
    op.alter_column('flight_pack_grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('flight_pack_grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('flight_pack_fills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('flight_pack_fills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_concurrency_snapshots_bucket_ts'), table_name='concurrency_snapshots')
    op.create_index(op.f('ix_concurrency_snapshots_bucket_ts'), 'concurrency_snapshots', ['bucket_ts'], unique=False)
    op.create_unique_constraint(op.f('uq_concurrency_snapshots_bucket_ts'), 'concurrency_snapshots', ['bucket_ts'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_document_chunks_source_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_library_material_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_course_material_file_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_course_instance_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_rag_ingestion_state_source_type'), table_name='rag_ingestion_state')
    op.drop_index(op.f('ix_rag_ingestion_state_source_id'), table_name='rag_ingestion_state')
    op.drop_table('rag_ingestion_state')
    # ### end Alembic commands ###
