export const en = {
  meta: {
    direction: 'ltr',
  },
  app: {
    tabsLabel: 'Dashboard views',
    tabs: {
      leadership: 'Leadership',
      sat: 'SAT Section',
      instructor: 'Instructor',
      student: 'Student',
    },
  },
  common: {
    live: 'Live',
    light: 'Light',
    dark: 'Dark',
    search: 'Search',
    filters: 'Filters',
    reset: 'Reset',
    statusPrefix: 'Status',
    ownerPrefix: 'Owner',
    trendPrefix: 'Trend',
    switchTheme: {
      light: 'Switch to light mode',
      dark: 'Switch to dark mode',
    },
    toneLabels: {
      success: 'Success',
      warning: 'Warning',
      danger: 'Critical',
      info: 'Info',
    },
    languageLabels: {
      en: 'EN',
      ar: 'Arabic',
    },
  },
  filters: {
    course: 'Course',
    courseVersion: 'Course version',
    courseInstance: 'Course instance',
    student: 'Student',
    instructor: 'Instructor',
    dateRange: 'Date range',
    lesson: 'Lesson',
    trainingType: 'Training type',
    competency: 'Competency',
    aircraftSimulator: 'Aircraft / simulator',
    material: 'Material',
    evaluationType: 'Evaluation type',
    region: 'Region',
    serviceType: 'Service type',
    status: 'Status',
    options: {
      allCourses: 'All courses',
      satFoundation: 'SAT Foundation',
      advancedMath: 'Advanced Math',
      flightReadiness: 'Flight Readiness',
      allVersions: 'All versions',
      version2026Q3: '2026 Q3',
      version2026Q2: '2026 Q2',
      versionLegacy: 'Legacy',
      allInstances: 'All instances',
      morningCohort: 'Morning cohort',
      eveningCohort: 'Evening cohort',
      weekendCohort: 'Weekend cohort',
      allStudents: 'All students',
      atRiskStudents: 'At-risk students',
      weakStudents: 'Weak students',
      highPerformers: 'High performers',
      allInstructors: 'All instructors',
      internalInstructors: 'Internal instructors',
      externalInstructors: 'External instructors',
      last24Hours: 'Last 24 hours',
      last7Days: 'Last 7 days',
      last30Days: 'Last 30 days',
      allLessons: 'All lessons',
      algebraFunctions: 'Algebra functions',
      readingInference: 'Reading inference',
      simulatorBriefing: 'Simulator briefing',
      allTrainingTypes: 'All training types',
      classroom: 'Classroom',
      flight: 'Flight',
      simulator: 'Simulator',
      allCompetencies: 'All competencies',
      quantitativeReasoning: 'Quantitative reasoning',
      evidenceReading: 'Evidence reading',
      safetyProcedure: 'Safety procedure',
      allAircraftSimulators: 'All aircraft / simulators',
      a320Simulator: 'A320 simulator',
      b737Simulator: 'B737 simulator',
      cessna172: 'Cessna 172',
      allMaterials: 'All materials',
      lessonSlides: 'Lesson slides',
      practicePacket: 'Practice packet',
      reviewVideo: 'Review video',
      allEvaluationTypes: 'All evaluation types',
      quiz: 'Quiz',
      practicalEvaluation: 'Practical evaluation',
      finalAssessment: 'Final assessment',
      allRegions: 'All regions',
      northAmerica: 'North America',
      emea: 'EMEA',
      apac: 'APAC',
      allServices: 'All services',
      liveCourses: 'Live courses',
      selfPaced: 'Self-paced',
      assessments: 'Assessments',
      active: 'Active',
      atRisk: 'At risk',
      paused: 'Paused',
    },
  },
  views: {
    leadership: {
      title: 'Operations Dashboard',
      description: 'Filtered operational view for executive monitoring.',
      searchPlaceholder: 'Search metrics, cohorts, alerts',
      viewLabel: 'Leadership view',
    },
    sat: {
      title: 'SAT Section Dashboard',
      description:
        'Operational view for SAT readiness, practice velocity, and evaluation throughput.',
      searchPlaceholder: 'Search SAT cohorts, sessions, alerts',
      viewLabel: 'SAT view',
    },
    instructor: {
      title: 'Instructor Dashboard',
      description:
        'Operational view for instructor load, response speed, and delivery quality.',
      searchPlaceholder: 'Search instructors, sessions, cohorts',
      viewLabel: 'Instructor view',
    },
    student: {
      title: 'Student Dashboard',
      description:
        'Operational view for learner progress, study momentum, and goal completion.',
      searchPlaceholder: 'Search goals, lessons, evaluations',
      viewLabel: 'Student view',
    },
  },
  detailSections: {
    kpiSummary: 'KPI Category Summary',
    riskTable: 'Risk Logic / Status Table',
    exportReadiness: 'Export Readiness Summary',
    weakLessons: 'Top Weak Lessons',
    pendingActions: 'Pending Actions',
    alerts: 'Dashboard Alerts',
    empty: {
      kpiCategories: 'No KPI categories to display.',
      riskStatuses: 'No risk items to display.',
      exportReadiness: 'No export readiness items to display.',
      weakLessons: 'No weak lessons to display.',
      pendingActions: 'No pending actions to display.',
      coverage: 'No PDF coverage items to display.',
    },
    tableHeaders: {
      area: 'Area',
      owner: 'Owner',
      status: 'Status',
      nextStep: 'Next step',
    },
  },
  data: {
    shared: {
      trends: {
        usageVolume: {
          label: 'Usage volume',
          value: '92k',
          helperText: 'Last 12 operating windows',
        },
      },
      courses: {
        activeCourses: 'Active courses',
        completion: 'Completion',
        atRiskCourses: 'At-risk courses',
      },
      students: {
        activeStudents: 'Active students',
        attendance: 'Attendance',
        retentionRisk: 'Retention risk',
      },
      instructors: {
        activeInstructors: 'Active instructors',
        averageLoad: 'Average load',
        responseTime: 'Response time',
      },
      lessons: {
        lessonsDelivered: 'Lessons delivered',
        lessonCompletion: 'Completion',
        rescheduleRate: 'Reschedule rate',
      },
      materials: {
        published: 'Published',
        usageRate: 'Usage rate',
        reviewBacklog: 'Review backlog',
      },
      evaluations: {
        completed: 'Completed',
        averageScore: 'Average score',
        pendingReviews: 'Pending reviews',
      },
      simulators: {
        sessions: 'Sessions',
        passRate: 'Pass rate',
        retryRate: 'Retry rate',
      },
      apiExports: {
        exportJobs: 'Export jobs',
        apiLatency: 'API latency',
        syncSuccess: 'Sync success',
      },
      values: {
        supportResponse: '214 ms',
        instructorResponse: '11 min',
        apiLatency: '181 ms',
        feedbackSpeed: '14 min',
      },
    },
    kpiCategories: {
      course: 'Course KPIs',
      student: 'Student KPIs',
      instructor: 'Instructor KPIs',
      lesson: 'Lesson KPIs',
      material: 'Material KPIs',
      evaluation: 'Evaluation KPIs',
      simulator: 'Flight/Simulator KPIs',
      externalInstructor: 'External Instructor KPIs',
      apiExport: 'API Export KPIs',
      courseHelper: 'Active, completed, delayed, and revision-ready courses',
      studentHelper: 'Pass/fail, weak students, attendance, and progress risk',
      instructorHelper:
        'Workload, coordination, feedback, and schedule coverage',
      lessonHelper: 'Completion, weak lessons, duration, and structure quality',
      materialHelper: 'Usage, update needs, and review effectiveness',
      evaluationHelper:
        'Completion, compliance, item weakness, and scoring backlog',
      simulatorHelper: 'Planned vs completed hours, bookings, and readiness',
      externalInstructorHelper:
        'External coordination alerts and coverage readiness',
      apiExportHelper:
        'Export jobs, payload readiness, latency, and sync success',
    },
    pdf: {
      leadershipTitle: 'Leadership PDF Coverage',
      satTitle: 'SAT Section PDF Coverage',
      instructorTitle: 'Instructor PDF Coverage',
      studentTitle: 'Student PDF Coverage',
      completedCourses: 'Completed courses count',
      completedCoursesHelper: 'Courses closed in the selected operating window',
      studentPassFail: 'Student pass/fail rate',
      studentPassFailHelper:
        'Passed versus failed evaluations across active cohorts',
      trainingDelays: 'Training delays',
      trainingDelaysHelper: 'Sessions delayed beyond the operating threshold',
      plannedCompletedHours: 'Flight/simulator hours planned vs completed',
      plannedCompletedHoursHelper:
        'Planned training hours compared with completed hours',
      weakStudents: 'Weak students',
      weakStudentsHelper:
        'Students requiring intervention across current cohorts',
      materialEffectiveness: 'Material effectiveness',
      materialEffectivenessHelper: 'Measured by usage and post-review lift',
      evaluationCompliance: 'Evaluation compliance',
      evaluationComplianceHelper: 'Required evaluations completed on time',
      coursesByVersion: 'Courses by version',
      coursesByVersionHelper: 'Published course versions currently in use',
      lessonDurationIssues: 'Lesson duration issues',
      lessonDurationIssuesHelper: 'Lessons outside approved duration bands',
      materialsNeedingUpdate: 'Materials needing update',
      materialsNeedingUpdateHelper: 'Materials flagged for SAT content refresh',
      repeatedWeakQuizLessons: 'Repeated weak quiz lessons',
      repeatedWeakQuizLessonsHelper: 'Repeated weak quiz lessons',
      evaluationItemWeaknessTrends: 'Evaluation item weakness trends',
      evaluationItemWeaknessTrendsHelper: 'Recurring weak items across evaluation forms',
      courseStructureGaps: 'Course structure gaps',
      courseStructureGapsHelper: 'Missing prerequisites, sequence breaks, and lesson gaps',
      feedbackTrends: 'Feedback trends',
      feedbackTrendsHelper: 'Instructor and student feedback trend movement',
      coursesRequiringRevision: 'Courses requiring revision',
      coursesRequiringRevisionHelper: 'Courses ready for SAT quality review',
      todaysSchedule: "Today's schedule",
      todaysScheduleHelper: 'Instructor sessions scheduled today',
      pendingAttendance: 'Pending attendance',
      pendingAttendanceHelper: 'Sessions still waiting for attendance submission',
      pendingEvaluations: 'Pending evaluations',
      pendingEvaluationsHelper: 'Evaluations awaiting instructor action',
      weakStudentsByLesson: 'Weak students by lesson',
      weakStudentsByLessonHelper: 'Students grouped by lesson-level weakness',
      studentsDidNotReviewMaterial: 'Students who did not review material',
      studentsDidNotReviewMaterialHelper:
        'Students missing assigned material review',
      quizResults: 'Quiz results',
      quizResultsHelper: 'Latest quiz completion and performance summary',
      upcomingBookings: 'Upcoming flight/simulator bookings',
      upcomingBookingsHelper: 'Booked sessions in the next planning window',
      externalCoordinationAlerts: 'External instructor coordination alerts',
      externalCoordinationAlertsHelper: 'Open coordination items with external instructors',
      courseProgressStatus: 'Course progress status',
      courseProgressStatusHelper: 'Current course pacing against plan',
      courseSchedule: 'Course schedule',
      courseScheduleHelper: 'Upcoming lessons and required attendance windows',
      materials: 'Materials',
      materialsHelper: 'Assigned learning and review materials',
      completedLessons: 'Completed lessons',
      completedLessonsHelper: 'Lessons completed by the learner',
      pendingQuizzes: 'Pending quizzes',
      pendingQuizzesHelper: 'Quizzes still waiting for completion',
      weakLessons: 'Weak lessons',
      weakLessonsHelper: 'Weak lessons requiring focused review',
      recommendedReviewMaterial: 'Recommended review material',
      recommendedReviewMaterialHelper:
        'Material recommended from weak lesson signals',
      limitedEvaluationFeedback: 'Limited evaluation feedback',
      limitedEvaluationFeedbackHelper:
        'Visible evaluation feedback limited to learner-safe guidance',
      courseProgress: 'Course progress',
      courseProgressHelper: 'Overall course completion and pacing',
    },
    alerts: {
      latencyTitle: 'Assessment scoring queue above target',
      latencyDescription:
        'Average scoring delay is 9.8 minutes across APAC cohorts.',
      attendanceTitle: 'Attendance dipped in evening instructor blocks',
      attendanceDescription: 'Two cohorts are below the 90% attendance target.',
    },
    leadership: {
      activeLearners: 'Active learners',
      activeLearnersHelper: '+5.2% vs previous hour',
      courseHealth: 'Course health',
      courseHealthHelper: 'Healthy operating range',
      supportResponse: 'Support response',
      supportResponseHelper: '-15 ms vs target',
    },
    sat: {
      activeCandidates: 'Active SAT candidates',
      activeCandidatesHelper: '+3.1% vs previous day',
      completion: 'Completion',
      practiceCompletion: 'Practice completion',
      practiceCompletionHelper: '+2.4% this week',
    },
    instructor: {
      liveSessions: 'Live sessions',
      liveSessionsHelper: 'Currently scheduled',
      feedbackSpeed: 'Feedback speed',
      feedbackSpeedHelper: 'Median response time',
    },
    student: {
      studyStreak: 'Study streak',
      studyStreakValue: '18 days',
      studyStreakHelper: 'Personal learning momentum',
      goalProgress: 'Goal progress',
      goalProgressHelper: 'Current plan completion',
    },
    details: {
      risks: {
        apacQueue: 'APAC scoring queue',
        assessmentOps: 'Assessment Ops',
        aboveTarget: 'Above target',
        rebalance: 'Rebalance scoring capacity',
        eveningCohorts: 'Evening cohorts',
        programLeads: 'Program Leads',
        watch: 'Watch',
        reviewCoverage: 'Review instructor coverage',
        partnerExports: 'Partner exports',
        platformOps: 'Platform Ops',
        ready: 'Ready',
        monitorSync: 'Monitor daily sync',
      },
      lessons: {
        algebraFunctions: 'Algebra functions',
        satPrepA: 'SAT Prep A',
        readingInference: 'Reading inference',
        satPrepC: 'SAT Prep C',
        essayStructure: 'Essay structure',
        writingLab: 'Writing Lab',
        linearEquations: 'Linear equations',
        satMath11: 'SAT Math 11',
        commandEvidence: 'Command of evidence',
        satReading08: 'SAT Reading 08',
        dataAnalysis: 'Data analysis',
        satMath14: 'SAT Math 14',
      },
      actions: {
        approveCapacity: 'Approve scoring queue capacity plan',
        opsDirector: 'Ops Director',
        today: 'Today',
        confirmCoverage: 'Confirm evening cohort coverage',
        regionalLead: 'Regional Lead',
        tomorrow: 'Tomorrow',
        reviewAudit: 'Review weekly audit',
        friday: 'Friday',
        reviewStudyPlan: 'Review study plan adjustment',
        studentCoach: 'Student Coach',
        schedulePractice: 'Schedule next practice test',
        learner: 'Learner',
        assignReview: 'Assign weak lesson review set',
        instructor: 'Instructor',
      },
      exports: {
        lmsExport: 'LMS export',
        partnerApi: 'Partner API',
        evaluationPayloads: 'Evaluation payloads',
        pending143: '143 pending',
      },
      instructor: {
        instructorLoad: 'Instructor load',
        scheduling: 'Scheduling',
        redistributeSessions: 'Redistribute evening sessions',
        feedbackQueue: 'Feedback queue',
        instructorLeads: 'Instructor leads',
        onTarget: 'On target',
        maintainCadence: 'Maintain cadence',
        weekendCoverage: 'Weekend coverage',
        regionalOps: 'Regional Ops',
        open: 'Open',
        confirmRoster: 'Confirm substitute roster',
      },
    },
  },
};